// SRD 5.1 classes, levels 1-20.
//
// This is the mechanical source of truth for character progression. Every entry
// in `features` is tagged with the level that grants it, so "features match the
// character's level" is a query, not a judgement call; the validator rebuilds
// the expected feature list from this table and compares it to the sheet.
//
// Spellcasting is described by pointing at a progression curve in
// rules/srd51/progression.js rather than restating slot counts per class.
// `cantripsKnown` and `spellsKnown` are indexed by level (index 0 unused).
//
// Each class carries the single subclass the SRD publishes for it. Subclass
// features are tagged with `subclass` and filtered in when that branch is taken.

const asi = (level) => ({
  level, name: 'Ability Score Improvement', kind: 'asi',
  description: 'Increase one ability score by 2, or two ability scores by 1 each, to a maximum of 20. Alternatively, take a feat.',
});

const CANTRIPS_3_4_5 = [0, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5];
const CANTRIPS_2_3_4 = [0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4];
const CANTRIPS_4_5_6 = [0, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6];

export const CLASSES = [
  {
    slug: 'barbarian', name: 'Barbarian', hitDie: 12,
    savingThrows: ['str', 'con'],
    armorProficiencies: ['light', 'medium', 'shields'],
    weaponProficiencies: ['simple', 'martial'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['animal-handling', 'athletics', 'intimidation', 'nature', 'perception', 'survival']
        .map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: null,
    subclassLevel: 3, subclassLabel: 'Primal Path',
    subclasses: [{ slug: 'berserker', name: 'Path of the Berserker' }],
    startingKit: { pack: 'srd51:gear.explorers-pack', extras: ['srd51:weapon.handaxe', 'srd51:weapon.javelin'] },
    tags: ['martial', 'melee', 'brute', 'unarmored'],
    features: [
      { level: 1, name: 'Rage', description: 'Enter a rage as a bonus action: advantage on Strength checks and saves, bonus melee damage, and resistance to bludgeoning, piercing, and slashing damage.', resources: [{ name: 'Rage', perLevel: [0, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 999], recharge: 'long rest' }], modifiers: [{ type: 'rage-damage', perLevel: [0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4] }] },
      { level: 1, name: 'Unarmored Defense', description: 'While wearing no armor, your AC equals 10 + your Dexterity modifier + your Constitution modifier. You may use a shield.', modifiers: [{ type: 'unarmored-defense', base: 10, abilities: ['dex', 'con'], allowShield: true }] },
      { level: 2, name: 'Reckless Attack', description: 'Gain advantage on Strength-based melee attack rolls this turn; attacks against you have advantage until your next turn.' },
      { level: 2, name: 'Danger Sense', description: 'Advantage on Dexterity saving throws against effects you can see.' },
      { level: 3, name: 'Frenzy', subclass: 'berserker', description: 'When you rage, you can frenzy to make a single melee weapon attack as a bonus action on each of your turns, gaining a level of exhaustion when the rage ends.' },
      asi(4),
      { level: 5, name: 'Extra Attack', description: 'Attack twice when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 2 }] },
      { level: 5, name: 'Fast Movement', description: 'Speed increases by 10 feet while not wearing heavy armor.', modifiers: [{ type: 'speed-bonus', value: 10, condition: 'not wearing heavy armor' }] },
      { level: 6, name: 'Mindless Rage', subclass: 'berserker', description: 'You cannot be charmed or frightened while raging.' },
      { level: 7, name: 'Feral Instinct', description: 'Advantage on initiative rolls, and you can act while surprised if you rage first.' },
      asi(8),
      { level: 9, name: 'Brutal Critical (1 die)', description: 'Roll one additional weapon damage die on a critical hit with a melee attack.' },
      { level: 10, name: 'Intimidating Presence', subclass: 'berserker', description: 'Frighten a creature within 30 feet with a Wisdom saving throw against DC 8 + proficiency bonus + Charisma modifier.' },
      { level: 11, name: 'Relentless Rage', description: 'When dropped to 0 hit points while raging, make a DC 10 Constitution save to drop to 1 instead.' },
      asi(12),
      { level: 13, name: 'Brutal Critical (2 dice)', description: 'Roll two additional weapon damage dice on a melee critical hit.' },
      { level: 14, name: 'Retaliation', subclass: 'berserker', description: 'When damaged by a creature within 5 feet, use your reaction to make a melee weapon attack against it.' },
      { level: 15, name: 'Persistent Rage', description: 'Your rage ends early only if you fall unconscious or choose to end it.' },
      asi(16),
      { level: 17, name: 'Brutal Critical (3 dice)', description: 'Roll three additional weapon damage dice on a melee critical hit.' },
      { level: 18, name: 'Indomitable Might', description: 'If your Strength check total is less than your Strength score, use the score instead.' },
      asi(19),
      { level: 20, name: 'Primal Champion', description: 'Strength and Constitution increase by 4, to a maximum of 24.', modifiers: [{ type: 'ability-increase', ability: 'str', value: 4, max: 24 }, { type: 'ability-increase', ability: 'con', value: 4, max: 24 }] },
    ],
  },

  {
    slug: 'bard', name: 'Bard', hitDie: 8,
    savingThrows: ['dex', 'cha'],
    armorProficiencies: ['light'],
    weaponProficiencies: ['simple', 'srd51:weapon.crossbow-hand', 'srd51:weapon.longsword', 'srd51:weapon.rapier', 'srd51:weapon.shortsword'],
    toolProficiencies: ['three musical instruments of your choice'],
    skillChoices: { count: 3, from: 'any' },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'full', ability: 'cha', prepares: false, ritual: true,
      listSlug: 'bard',
      cantripsKnown: CANTRIPS_2_3_4,
      spellsKnown: [0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 15, 16, 18, 19, 19, 20, 22, 22, 22],
    },
    subclassLevel: 3, subclassLabel: 'Bard College',
    subclasses: [{ slug: 'lore', name: 'College of Lore' }],
    startingKit: { pack: 'srd51:gear.entertainers-pack', extras: ['srd51:gear.lute'] },
    tags: ['caster', 'face', 'support', 'skills'],
    features: [
      { level: 1, name: 'Spellcasting', description: 'You cast bard spells using Charisma. Spell save DC = 8 + proficiency bonus + Charisma modifier.' },
      { level: 1, name: 'Bardic Inspiration', description: 'As a bonus action, give a creature an inspiration die it can add to one ability check, attack roll, or saving throw.', resources: [{ name: 'Bardic Inspiration', formula: 'cha-mod-min-1', recharge: 'long rest' }], modifiers: [{ type: 'scaling-die', name: 'Bardic Inspiration', perLevel: [0, 6, 6, 6, 6, 8, 8, 8, 8, 8, 10, 10, 10, 10, 10, 12, 12, 12, 12, 12, 12] }] },
      { level: 2, name: 'Jack of All Trades', description: 'Add half your proficiency bonus, rounded down, to any ability check that does not already include it.', modifiers: [{ type: 'half-proficiency-all-checks' }] },
      { level: 2, name: 'Song of Rest', description: 'During a short rest, allies who spend Hit Dice regain extra hit points.' },
      { level: 3, name: 'Expertise', description: 'Choose two skill proficiencies; your proficiency bonus is doubled for them.', modifiers: [{ type: 'expertise', count: 2 }] },
      { level: 3, name: 'Bonus Proficiencies', subclass: 'lore', description: 'Gain proficiency with three skills of your choice.', modifiers: [{ type: 'skill-choice', count: 3 }] },
      { level: 3, name: 'Cutting Words', subclass: 'lore', description: 'Use your reaction and a Bardic Inspiration die to subtract from an enemy roll.' },
      asi(4),
      { level: 5, name: 'Font of Inspiration', description: 'Regain all Bardic Inspiration uses on a short or long rest.' },
      { level: 6, name: 'Countercharm', description: 'Grant allies advantage on saves against being frightened or charmed.' },
      { level: 6, name: 'Additional Magical Secrets', subclass: 'lore', description: 'Learn two spells from any class, which do not count against your spells known.', modifiers: [{ type: 'magical-secrets', count: 2 }] },
      asi(8),
      { level: 10, name: 'Expertise', description: 'Choose two more skill proficiencies to double your proficiency bonus for.', modifiers: [{ type: 'expertise', count: 2 }] },
      { level: 10, name: 'Magical Secrets', description: 'Learn two spells from any class.', modifiers: [{ type: 'magical-secrets', count: 2 }] },
      asi(12),
      { level: 14, name: 'Magical Secrets', description: 'Learn two more spells from any class.', modifiers: [{ type: 'magical-secrets', count: 2 }] },
      { level: 14, name: 'Peerless Skill', subclass: 'lore', description: 'Add a Bardic Inspiration die to your own ability check.' },
      asi(16),
      { level: 18, name: 'Magical Secrets', description: 'Learn two more spells from any class.', modifiers: [{ type: 'magical-secrets', count: 2 }] },
      asi(19),
      { level: 20, name: 'Superior Inspiration', description: 'Regain one Bardic Inspiration use when you roll initiative with none left.' },
    ],
  },

  {
    slug: 'cleric', name: 'Cleric', hitDie: 8,
    savingThrows: ['wis', 'cha'],
    armorProficiencies: ['light', 'medium', 'shields'],
    weaponProficiencies: ['simple'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['history', 'insight', 'medicine', 'persuasion', 'religion'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'full', ability: 'wis', prepares: true, ritual: true,
      listSlug: 'cleric', preparedFormula: 'ability+level',
      cantripsKnown: CANTRIPS_3_4_5,
    },
    subclassLevel: 1, subclassLabel: 'Divine Domain',
    subclasses: [{ slug: 'life', name: 'Life Domain' }],
    startingKit: { pack: 'srd51:gear.priests-pack', extras: ['srd51:gear.holy-symbol'], focus: 'divine' },
    tags: ['caster', 'healer', 'divine-caster', 'support'],
    features: [
      { level: 1, name: 'Spellcasting', description: 'You cast cleric spells using Wisdom, preparing them from the full cleric list after a long rest.' },
      { level: 1, name: 'Bonus Proficiency', subclass: 'life', description: 'Gain proficiency with heavy armor.', modifiers: [{ type: 'armor-proficiency', categories: ['heavy'] }] },
      { level: 1, name: 'Disciple of Life', subclass: 'life', description: 'Healing spells of 1st level or higher restore an additional 2 + the spell level hit points.' },
      { level: 1, name: 'Domain Spells', subclass: 'life', description: 'Bless, cure wounds, lesser restoration, spiritual weapon, beacon of hope, revivify, death ward, guardian of faith, mass cure wounds, and raise dead are always prepared and do not count against your prepared total.', modifiers: [{ type: 'domain-spells', spells: ['srd51:spell.bless', 'srd51:spell.cure-wounds', 'srd51:spell.lesser-restoration', 'srd51:spell.spiritual-weapon', 'srd51:spell.beacon-of-hope', 'srd51:spell.revivify', 'srd51:spell.death-ward', 'srd51:spell.guardian-of-faith', 'srd51:spell.mass-cure-wounds', 'srd51:spell.raise-dead'] }] },
      { level: 2, name: 'Channel Divinity', description: 'Channel divine energy for a magical effect. Regain uses on a short or long rest.', resources: [{ name: 'Channel Divinity', perLevel: [0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3], recharge: 'short rest' }] },
      { level: 2, name: 'Channel Divinity: Turn Undead', description: 'Each undead within 30 feet must make a Wisdom save or be turned for 1 minute.' },
      { level: 2, name: 'Channel Divinity: Preserve Life', subclass: 'life', description: 'Restore hit points equal to five times your cleric level, divided among creatures within 30 feet.' },
      asi(4),
      { level: 5, name: 'Destroy Undead (CR 1/2)', description: 'Undead of CR 1/2 or lower are destroyed instead of turned.' },
      { level: 6, name: 'Blessed Healer', subclass: 'life', description: 'When you heal another creature with a spell, you regain 2 + the spell level hit points.' },
      asi(8),
      { level: 8, name: 'Destroy Undead (CR 1)', description: 'Undead of CR 1 or lower are destroyed instead of turned.' },
      { level: 8, name: 'Divine Strike', subclass: 'life', description: 'Once per turn, a weapon hit deals an extra 1d8 radiant damage, rising to 2d8 at 14th level.' },
      { level: 10, name: 'Divine Intervention', description: 'Call on your deity; succeeds on a percentile roll under your cleric level.' },
      { level: 11, name: 'Destroy Undead (CR 2)', description: 'Undead of CR 2 or lower are destroyed instead of turned.' },
      asi(12),
      { level: 14, name: 'Destroy Undead (CR 3)', description: 'Undead of CR 3 or lower are destroyed instead of turned.' },
      asi(16),
      { level: 17, name: 'Destroy Undead (CR 4)', description: 'Undead of CR 4 or lower are destroyed instead of turned.' },
      { level: 17, name: 'Supreme Healing', subclass: 'life', description: 'Healing dice are treated as rolling their maximum.' },
      { level: 18, name: 'Channel Divinity (3/rest)', description: 'Use Channel Divinity three times between rests.' },
      asi(19),
      { level: 20, name: 'Divine Intervention Improvement', description: 'Your call for intervention automatically succeeds.' },
    ],
  },

  {
    slug: 'druid', name: 'Druid', hitDie: 8,
    savingThrows: ['int', 'wis'],
    armorProficiencies: ['light', 'medium', 'shields'],
    armorRestriction: 'Druids will not wear armor or use shields made of metal.',
    weaponProficiencies: ['srd51:weapon.club', 'srd51:weapon.dagger', 'srd51:weapon.dart', 'srd51:weapon.javelin', 'srd51:weapon.mace', 'srd51:weapon.quarterstaff', 'srd51:weapon.scimitar', 'srd51:weapon.sickle', 'srd51:weapon.sling', 'srd51:weapon.spear'],
    toolProficiencies: ['Herbalism kit'],
    skillChoices: {
      count: 2,
      from: ['arcana', 'animal-handling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'full', ability: 'wis', prepares: true, ritual: true,
      listSlug: 'druid', preparedFormula: 'ability+level',
      cantripsKnown: CANTRIPS_2_3_4,
    },
    subclassLevel: 2, subclassLabel: 'Druid Circle',
    subclasses: [{ slug: 'land', name: 'Circle of the Land' }],
    startingKit: { pack: 'srd51:gear.explorers-pack', extras: ['srd51:gear.druidic-focus', 'srd51:gear.herbalism-kit'], focus: 'druidic' },
    tags: ['caster', 'controller', 'support', 'nature'],
    features: [
      { level: 1, name: 'Druidic', description: 'You know Druidic, the secret language of druids.' },
      { level: 1, name: 'Spellcasting', description: 'You cast druid spells using Wisdom, preparing them from the full druid list after a long rest.' },
      { level: 2, name: 'Wild Shape', description: 'Magically assume the shape of a beast you have seen, twice per short or long rest.', resources: [{ name: 'Wild Shape', amount: 2, recharge: 'short rest' }] },
      { level: 2, name: 'Bonus Cantrip', subclass: 'land', description: 'Learn one additional druid cantrip.', modifiers: [{ type: 'bonus-cantrip', classSlug: 'druid', ability: 'wis', count: 1 }] },
      { level: 2, name: 'Natural Recovery', subclass: 'land', description: 'Recover expended spell slots during a short rest, once per long rest.' },
      { level: 3, name: 'Circle Spells', subclass: 'land', description: 'Your circle terrain grants additional always-prepared spells.' },
      asi(4),
      { level: 4, name: 'Wild Shape Improvement', description: 'You can transform into a beast of challenge rating 1/2 without a flying speed.' },
      { level: 6, name: "Land's Stride", subclass: 'land', description: 'Move through nonmagical difficult terrain without cost, and gain advantage on saves against plants that impede movement.' },
      asi(8),
      { level: 8, name: 'Wild Shape Improvement', description: 'You can transform into a beast of challenge rating 1.' },
      { level: 10, name: "Nature's Ward", subclass: 'land', description: 'You cannot be charmed or frightened by elementals or fey, and are immune to poison and disease.', modifiers: [{ type: 'condition-immunity', conditions: ['poisoned'] }] },
      asi(12),
      { level: 14, name: "Nature's Sanctuary", subclass: 'land', description: 'Beasts and plants must succeed on a Wisdom save to attack you.' },
      asi(16),
      { level: 18, name: 'Timeless Body', description: 'You age more slowly.' },
      { level: 18, name: 'Beast Spells', description: 'Cast druid spells in Wild Shape without material components.' },
      asi(19),
      { level: 20, name: 'Archdruid', description: 'Use Wild Shape an unlimited number of times.' },
    ],
  },

  {
    slug: 'fighter', name: 'Fighter', hitDie: 10,
    savingThrows: ['str', 'con'],
    armorProficiencies: ['light', 'medium', 'heavy', 'shields'],
    weaponProficiencies: ['simple', 'martial'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['acrobatics', 'animal-handling', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 6, 8, 12, 14, 16, 19],
    spellcasting: null,
    subclassLevel: 3, subclassLabel: 'Martial Archetype',
    subclasses: [{ slug: 'champion', name: 'Champion' }],
    startingKit: { pack: 'srd51:gear.dungeoneers-pack', extras: [] },
    tags: ['martial', 'melee', 'ranged', 'warrior', 'guardian'],
    features: [
      { level: 1, name: 'Fighting Style', kind: 'choice', description: 'Adopt a fighting style as your specialty.', choiceOptions: ['Archery', 'Defense', 'Dueling', 'Great Weapon Fighting', 'Protection', 'Two-Weapon Fighting'], modifiers: [{ type: 'fighting-style' }] },
      { level: 1, name: 'Second Wind', description: 'As a bonus action, regain 1d10 + fighter level hit points. Once per short or long rest.', resources: [{ name: 'Second Wind', amount: 1, recharge: 'short rest' }] },
      { level: 2, name: 'Action Surge', description: 'Take one additional action on your turn. Once per short or long rest.', resources: [{ name: 'Action Surge', perLevel: [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2], recharge: 'short rest' }] },
      { level: 3, name: 'Improved Critical', subclass: 'champion', description: 'Your weapon attacks score a critical hit on a roll of 19 or 20.' },
      asi(4),
      { level: 5, name: 'Extra Attack', description: 'Attack twice when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 2 }] },
      asi(6),
      { level: 7, name: 'Remarkable Athlete', subclass: 'champion', description: 'Add half your proficiency bonus to Strength, Dexterity, and Constitution checks that do not already include it, and increase your running long jump.' },
      asi(8),
      { level: 9, name: 'Indomitable', description: 'Reroll a failed saving throw. Once per long rest.', resources: [{ name: 'Indomitable', perLevel: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], recharge: 'long rest' }] },
      { level: 10, name: 'Additional Fighting Style', subclass: 'champion', description: 'Choose a second fighting style.', modifiers: [{ type: 'fighting-style' }] },
      { level: 11, name: 'Extra Attack (2)', description: 'Attack three times when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 3 }] },
      asi(12),
      asi(14),
      { level: 15, name: 'Superior Critical', subclass: 'champion', description: 'Your weapon attacks score a critical hit on a roll of 18-20.' },
      asi(16),
      { level: 18, name: 'Survivor', subclass: 'champion', description: 'Regain hit points at the start of each of your turns while below half your hit point maximum.' },
      asi(19),
      { level: 20, name: 'Extra Attack (3)', description: 'Attack four times when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 4 }] },
    ],
  },

  {
    slug: 'monk', name: 'Monk', hitDie: 8,
    savingThrows: ['str', 'dex'],
    armorProficiencies: [],
    weaponProficiencies: ['simple', 'srd51:weapon.shortsword'],
    toolProficiencies: ["one type of artisan's tools or one musical instrument"],
    skillChoices: {
      count: 2,
      from: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: null,
    subclassLevel: 3, subclassLabel: 'Monastic Tradition',
    subclasses: [{ slug: 'open-hand', name: 'Way of the Open Hand' }],
    startingKit: { pack: 'srd51:gear.explorers-pack', extras: ['srd51:weapon.dart'] },
    tags: ['martial', 'melee', 'skirmisher', 'unarmored'],
    features: [
      { level: 1, name: 'Unarmored Defense', description: 'While wearing no armor and no shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier.', modifiers: [{ type: 'unarmored-defense', base: 10, abilities: ['dex', 'wis'], allowShield: false }] },
      { level: 1, name: 'Martial Arts', description: 'Use Dexterity for unarmed strikes and monk weapons, roll a martial arts die for their damage, and make an unarmed strike as a bonus action after attacking.', modifiers: [{ type: 'martial-arts-die', perLevel: [0, 4, 4, 4, 4, 6, 6, 6, 6, 6, 8, 8, 8, 8, 8, 8, 10, 10, 10, 10, 10] }] },
      { level: 2, name: 'Ki', description: 'Fuel special techniques with ki points equal to your monk level, regained on a short or long rest.', resources: [{ name: 'Ki', formula: 'level', recharge: 'short rest' }] },
      { level: 2, name: 'Unarmored Movement', description: 'Your speed increases while you wear no armor and no shield.', modifiers: [{ type: 'unarmored-movement', perLevel: [0, 0, 10, 10, 10, 10, 15, 15, 15, 15, 20, 20, 20, 20, 25, 25, 25, 25, 30, 30, 30] }] },
      { level: 3, name: 'Deflect Missiles', description: 'Use your reaction to reduce ranged weapon damage by 1d10 + monk level + Dexterity modifier.' },
      { level: 3, name: 'Open Hand Technique', subclass: 'open-hand', description: 'Flurry of Blows attacks can knock prone, push 15 feet, or deny reactions.' },
      asi(4),
      { level: 4, name: 'Slow Fall', description: 'Reduce falling damage by five times your monk level.' },
      { level: 5, name: 'Extra Attack', description: 'Attack twice when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 2 }] },
      { level: 5, name: 'Stunning Strike', description: 'Spend 1 ki to force a Constitution save or stun a creature you hit until the end of your next turn.' },
      { level: 6, name: 'Ki-Empowered Strikes', description: 'Your unarmed strikes count as magical.' },
      { level: 6, name: 'Wholeness of Body', subclass: 'open-hand', description: 'Regain hit points equal to three times your monk level, once per long rest.' },
      { level: 7, name: 'Evasion', description: 'Take no damage on a successful Dexterity save against area effects, and half on a failure.' },
      { level: 7, name: 'Stillness of Mind', description: 'End one effect charming or frightening you.' },
      asi(8),
      { level: 10, name: 'Purity of Body', description: 'Immunity to disease and poison.', modifiers: [{ type: 'condition-immunity', conditions: ['poisoned'] }] },
      { level: 11, name: 'Tranquility', subclass: 'open-hand', description: 'Gain the effect of a sanctuary spell between long rests.' },
      asi(12),
      { level: 13, name: 'Tongue of the Sun and Moon', description: 'Understand all spoken languages.' },
      { level: 14, name: 'Diamond Soul', description: 'Proficiency in all saving throws, and reroll failed saves by spending 1 ki.', modifiers: [{ type: 'all-save-proficiency' }] },
      { level: 15, name: 'Timeless Body', description: 'You no longer age and need no food or water.' },
      asi(16),
      { level: 17, name: 'Quivering Palm', subclass: 'open-hand', description: 'Set up lethal vibrations in a creature you hit, triggered later for 10d10 necrotic damage.' },
      { level: 18, name: 'Empty Body', description: 'Spend ki to become invisible, or to cast astral projection.' },
      asi(19),
      { level: 20, name: 'Perfect Self', description: 'Regain 4 ki points when you roll initiative with none left.' },
    ],
  },

  {
    slug: 'paladin', name: 'Paladin', hitDie: 10,
    savingThrows: ['wis', 'cha'],
    armorProficiencies: ['light', 'medium', 'heavy', 'shields'],
    weaponProficiencies: ['simple', 'martial'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'half', ability: 'cha', prepares: true, ritual: false,
      listSlug: 'paladin', preparedFormula: 'ability+half-level', startLevel: 2,
      cantripsKnown: null,
    },
    subclassLevel: 3, subclassLabel: 'Sacred Oath',
    subclasses: [{ slug: 'devotion', name: 'Oath of Devotion' }],
    startingKit: { pack: 'srd51:gear.priests-pack', extras: ['srd51:gear.holy-symbol', 'srd51:weapon.javelin'], focus: 'divine' },
    tags: ['martial', 'melee', 'guardian', 'divine-caster', 'healer'],
    features: [
      { level: 1, name: 'Divine Sense', description: 'Detect celestials, fiends, and undead within 60 feet. Uses equal to 1 + Charisma modifier per long rest.', resources: [{ name: 'Divine Sense', formula: 'cha-mod-plus-1', recharge: 'long rest' }] },
      { level: 1, name: 'Lay on Hands', description: 'A pool of healing equal to five times your paladin level, restored on a long rest.', resources: [{ name: 'Lay on Hands', formula: 'level-x5', recharge: 'long rest' }] },
      { level: 2, name: 'Fighting Style', kind: 'choice', description: 'Adopt a fighting style as your specialty.', choiceOptions: ['Defense', 'Dueling', 'Great Weapon Fighting', 'Protection'], modifiers: [{ type: 'fighting-style' }] },
      { level: 2, name: 'Spellcasting', description: 'You cast paladin spells using Charisma, preparing them from the paladin list after a long rest.' },
      { level: 2, name: 'Divine Smite', description: 'Expend a spell slot when you hit with a melee weapon attack to deal 2d8 radiant damage, plus 1d8 per slot level above 1st.' },
      { level: 3, name: 'Divine Health', description: 'You are immune to disease.' },
      { level: 3, name: 'Channel Divinity: Sacred Weapon', subclass: 'devotion', description: 'Add your Charisma modifier to attack rolls with a weapon, which emits light and counts as magical.', resources: [{ name: 'Channel Divinity', amount: 1, recharge: 'short rest' }] },
      { level: 3, name: 'Channel Divinity: Turn the Unholy', subclass: 'devotion', description: 'Force fiends and undead within 30 feet to make a Wisdom save or be turned.' },
      { level: 3, name: 'Oath Spells', subclass: 'devotion', description: 'Protection from evil and good, sanctuary, lesser restoration, zone of truth, beacon of hope, dispel magic, freedom of movement, guardian of faith, commune, and flame strike are always prepared.', modifiers: [{ type: 'domain-spells', spells: ['srd51:spell.protection-from-evil-and-good', 'srd51:spell.sanctuary', 'srd51:spell.lesser-restoration', 'srd51:spell.zone-of-truth', 'srd51:spell.beacon-of-hope', 'srd51:spell.dispel-magic', 'srd51:spell.freedom-of-movement', 'srd51:spell.guardian-of-faith', 'srd51:spell.commune', 'srd51:spell.flame-strike'] }] },
      asi(4),
      { level: 5, name: 'Extra Attack', description: 'Attack twice when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 2 }] },
      { level: 6, name: 'Aura of Protection', description: 'You and friendly creatures within 10 feet add your Charisma modifier to saving throws.' },
      { level: 7, name: 'Aura of Devotion', subclass: 'devotion', description: 'You and friendly creatures within 10 feet cannot be charmed.' },
      asi(8),
      { level: 10, name: 'Aura of Courage', description: 'You and friendly creatures within 10 feet cannot be frightened.' },
      { level: 11, name: 'Improved Divine Smite', description: 'Your melee weapon hits deal an extra 1d8 radiant damage.' },
      asi(12),
      { level: 14, name: 'Cleansing Touch', description: 'End one spell on yourself or a willing creature, Charisma modifier times per long rest.' },
      { level: 15, name: 'Purity of Spirit', subclass: 'devotion', description: 'You are always under the effect of a protection from evil and good spell.' },
      asi(16),
      { level: 18, name: 'Aura Improvements', description: 'Your auras extend to 30 feet.' },
      asi(19),
      { level: 20, name: 'Holy Nimbus', subclass: 'devotion', description: 'Emanate sunlight that damages fiends and undead and grants advantage on saves against their spells.' },
    ],
  },

  {
    slug: 'ranger', name: 'Ranger', hitDie: 10,
    savingThrows: ['str', 'dex'],
    armorProficiencies: ['light', 'medium', 'shields'],
    weaponProficiencies: ['simple', 'martial'],
    toolProficiencies: [],
    skillChoices: {
      count: 3,
      from: ['animal-handling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'half', ability: 'wis', prepares: false, ritual: false,
      listSlug: 'ranger', startLevel: 2, cantripsKnown: null,
      spellsKnown: [0, 0, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11],
    },
    subclassLevel: 3, subclassLabel: 'Ranger Archetype',
    subclasses: [{ slug: 'hunter', name: 'Hunter' }],
    startingKit: { pack: 'srd51:gear.explorers-pack', extras: ['srd51:gear.arrows'] },
    tags: ['martial', 'ranged', 'scout', 'archer', 'nature'],
    features: [
      { level: 1, name: 'Favored Enemy', kind: 'choice', description: 'Advantage on Survival checks to track your favored enemies and on Intelligence checks to recall information about them. You learn one language they speak.', choiceOptions: ['Beasts', 'Fey', 'Humanoids', 'Monstrosities', 'Undead', 'Aberrations', 'Dragons', 'Giants'] },
      { level: 1, name: 'Natural Explorer', kind: 'choice', description: 'Your proficiency bonus is doubled for Intelligence and Wisdom checks about your favored terrain, and your party gains travel benefits there.', choiceOptions: ['Arctic', 'Coast', 'Desert', 'Forest', 'Grassland', 'Mountain', 'Swamp', 'Underdark'] },
      { level: 2, name: 'Fighting Style', kind: 'choice', description: 'Adopt a fighting style as your specialty.', choiceOptions: ['Archery', 'Defense', 'Dueling', 'Two-Weapon Fighting'], modifiers: [{ type: 'fighting-style' }] },
      { level: 2, name: 'Spellcasting', description: 'You cast ranger spells using Wisdom.' },
      { level: 3, name: "Hunter's Prey", subclass: 'hunter', kind: 'choice', description: 'Choose Colossus Slayer, Giant Killer, or Horde Breaker.', choiceOptions: ['Colossus Slayer', 'Giant Killer', 'Horde Breaker'] },
      { level: 3, name: 'Primeval Awareness', description: 'Expend a spell slot to sense whether certain creature types are within a radius.' },
      asi(4),
      { level: 5, name: 'Extra Attack', description: 'Attack twice when you take the Attack action.', modifiers: [{ type: 'extra-attack', count: 2 }] },
      { level: 6, name: 'Favored Enemy and Natural Explorer Improvements', description: 'Choose an additional favored enemy and an additional favored terrain.' },
      { level: 7, name: 'Defensive Tactics', subclass: 'hunter', kind: 'choice', description: 'Choose Escape the Horde, Multiattack Defense, or Steel Will.', choiceOptions: ['Escape the Horde', 'Multiattack Defense', 'Steel Will'] },
      asi(8),
      { level: 8, name: "Land's Stride", description: 'Move through nonmagical difficult terrain without cost.' },
      { level: 10, name: 'Hide in Plain Sight', description: 'Spend a minute camouflaging yourself for a +10 bonus to Stealth checks while you remain still.' },
      { level: 11, name: 'Multiattack', subclass: 'hunter', kind: 'choice', description: 'Choose Volley or Whirlwind Attack.', choiceOptions: ['Volley', 'Whirlwind Attack'] },
      asi(12),
      { level: 14, name: 'Vanish', description: 'Hide as a bonus action, and you cannot be tracked by nonmagical means.' },
      { level: 15, name: "Superior Hunter's Defense", subclass: 'hunter', kind: 'choice', description: 'Choose Evasion, Stand Against the Tide, or Uncanny Dodge.', choiceOptions: ['Evasion', 'Stand Against the Tide', 'Uncanny Dodge'] },
      asi(16),
      { level: 18, name: 'Feral Senses', description: 'You are aware of the location of invisible creatures within 30 feet.', modifiers: [{ type: 'sense', sense: 'blindsight', range: 30 }] },
      asi(19),
      { level: 20, name: 'Foe Slayer', description: 'Once per turn, add your Wisdom modifier to an attack roll or damage roll against a favored enemy.' },
    ],
  },

  {
    slug: 'rogue', name: 'Rogue', hitDie: 8,
    savingThrows: ['dex', 'int'],
    armorProficiencies: ['light'],
    weaponProficiencies: ['simple', 'srd51:weapon.crossbow-hand', 'srd51:weapon.longsword', 'srd51:weapon.rapier', 'srd51:weapon.shortsword'],
    toolProficiencies: ["Thieves' tools"],
    skillChoices: {
      count: 4,
      from: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleight-of-hand', 'stealth'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 10, 12, 16, 19],
    spellcasting: null,
    subclassLevel: 3, subclassLabel: 'Roguish Archetype',
    subclasses: [{ slug: 'thief', name: 'Thief' }],
    startingKit: { pack: 'srd51:gear.burglars-pack', extras: ['srd51:gear.thieves-tools'] },
    tags: ['martial', 'skirmisher', 'scout', 'expert', 'ambusher'],
    features: [
      { level: 1, name: 'Expertise', description: 'Choose two skill proficiencies, or one skill and thieves’ tools; your proficiency bonus is doubled for them.', modifiers: [{ type: 'expertise', count: 2 }] },
      { level: 1, name: 'Sneak Attack', description: 'Once per turn, deal extra damage to a creature you hit with a finesse or ranged weapon when you have advantage or an ally is adjacent.', modifiers: [{ type: 'sneak-attack-dice', formula: 'ceil(level/2)' }] },
      { level: 1, name: "Thieves' Cant", description: 'You know the secret mix of dialect, jargon, and code used by rogues.' },
      { level: 2, name: 'Cunning Action', description: 'Dash, Disengage, or Hide as a bonus action.' },
      { level: 3, name: 'Fast Hands', subclass: 'thief', description: 'Use your Cunning Action bonus action for Sleight of Hand, thieves’ tools, or the Use an Object action.' },
      { level: 3, name: 'Second-Story Work', subclass: 'thief', description: 'Climbing costs no extra movement, and your running jump distance increases by your Dexterity modifier.' },
      asi(4),
      { level: 5, name: 'Uncanny Dodge', description: 'Use your reaction to halve the damage of an attack you can see.' },
      { level: 6, name: 'Expertise', description: 'Choose two more proficiencies to double your proficiency bonus for.', modifiers: [{ type: 'expertise', count: 2 }] },
      { level: 7, name: 'Evasion', description: 'Take no damage on a successful Dexterity save against area effects, and half on a failure.' },
      asi(8),
      { level: 9, name: 'Supreme Sneak', subclass: 'thief', description: 'Advantage on Stealth checks if you move no more than half your speed on your turn.' },
      asi(10),
      { level: 11, name: 'Reliable Talent', description: 'Treat a d20 roll of 9 or lower as a 10 for ability checks with a proficient skill.' },
      asi(12),
      { level: 13, name: 'Use Magic Device', subclass: 'thief', description: 'Ignore class, race, and level requirements on the use of magic items.' },
      { level: 14, name: 'Blindsense', description: 'You are aware of the location of hidden or invisible creatures within 10 feet.', modifiers: [{ type: 'sense', sense: 'blindsense', range: 10 }] },
      { level: 15, name: 'Slippery Mind', description: 'Gain proficiency in Wisdom saving throws.', modifiers: [{ type: 'save-proficiency', abilities: ['wis'] }] },
      asi(16),
      { level: 17, name: "Thief's Reflexes", subclass: 'thief', description: 'Take two turns during the first round of combat.' },
      { level: 18, name: 'Elusive', description: 'No attack roll has advantage against you while you are not incapacitated.' },
      asi(19),
      { level: 20, name: 'Stroke of Luck', description: 'Turn a miss into a hit, or a failed check into a 20. Once per short or long rest.' },
    ],
  },

  {
    slug: 'sorcerer', name: 'Sorcerer', hitDie: 6,
    savingThrows: ['con', 'cha'],
    armorProficiencies: [],
    weaponProficiencies: ['srd51:weapon.dagger', 'srd51:weapon.dart', 'srd51:weapon.sling', 'srd51:weapon.quarterstaff', 'srd51:weapon.crossbow-light'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'full', ability: 'cha', prepares: false, ritual: false,
      listSlug: 'sorcerer',
      cantripsKnown: CANTRIPS_4_5_6,
      spellsKnown: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15],
    },
    subclassLevel: 1, subclassLabel: 'Sorcerous Origin',
    subclasses: [{ slug: 'draconic', name: 'Draconic Bloodline' }],
    startingKit: { pack: 'srd51:gear.dungeoneers-pack', extras: ['srd51:gear.arcane-focus'], focus: 'arcane' },
    tags: ['caster', 'arcane-caster', 'controller', 'artillery'],
    features: [
      { level: 1, name: 'Spellcasting', description: 'You cast sorcerer spells using Charisma.' },
      { level: 1, name: 'Dragon Ancestor', subclass: 'draconic', description: 'Choose a dragon type; you can speak Draconic and double your proficiency bonus on Charisma checks involving dragons.', modifiers: [{ type: 'language-grant', ids: ['srd51:language.draconic'] }] },
      { level: 1, name: 'Draconic Resilience', subclass: 'draconic', description: 'Your hit point maximum increases by 1 per sorcerer level, and while not wearing armor your AC equals 13 + your Dexterity modifier.', modifiers: [{ type: 'hp-per-level', value: 1 }, { type: 'unarmored-defense', base: 13, abilities: ['dex'], allowShield: true }] },
      { level: 2, name: 'Font of Magic', description: 'Sorcery points equal to your sorcerer level, convertible to and from spell slots.', resources: [{ name: 'Sorcery Points', formula: 'level', recharge: 'long rest' }] },
      { level: 3, name: 'Metamagic', description: 'Choose two Metamagic options to bend your spells.', modifiers: [{ type: 'metamagic', count: 2 }] },
      asi(4),
      { level: 6, name: 'Elemental Affinity', subclass: 'draconic', description: 'Add your Charisma modifier to one damage roll of a spell matching your dragon ancestry, and spend a sorcery point for resistance to that damage type.' },
      asi(8),
      { level: 10, name: 'Metamagic', description: 'Choose an additional Metamagic option.', modifiers: [{ type: 'metamagic', count: 1 }] },
      asi(12),
      { level: 14, name: 'Dragon Wings', subclass: 'draconic', description: 'Sprout wings and gain a flying speed equal to your current speed.', modifiers: [{ type: 'movement', mode: 'fly', matchWalk: true }] },
      asi(16),
      { level: 17, name: 'Metamagic', description: 'Choose an additional Metamagic option.', modifiers: [{ type: 'metamagic', count: 1 }] },
      { level: 18, name: 'Draconic Presence', subclass: 'draconic', description: 'Spend 5 sorcery points to awe or frighten creatures within 60 feet.' },
      asi(19),
      { level: 20, name: 'Sorcerous Restoration', description: 'Regain 4 sorcery points on a short rest.' },
    ],
  },

  {
    slug: 'warlock', name: 'Warlock', hitDie: 8,
    savingThrows: ['wis', 'cha'],
    armorProficiencies: ['light'],
    weaponProficiencies: ['simple'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'pact', ability: 'cha', prepares: false, ritual: false,
      listSlug: 'warlock',
      cantripsKnown: CANTRIPS_2_3_4,
      spellsKnown: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15],
    },
    subclassLevel: 1, subclassLabel: 'Otherworldly Patron',
    subclasses: [{ slug: 'fiend', name: 'The Fiend' }],
    startingKit: { pack: 'srd51:gear.scholars-pack', extras: ['srd51:gear.component-pouch'], focus: 'arcane' },
    tags: ['caster', 'arcane-caster', 'artillery', 'controller'],
    features: [
      { level: 1, name: 'Pact Magic', description: 'You cast warlock spells using Charisma. All your slots are the same level and return on a short rest.' },
      { level: 1, name: "Dark One's Blessing", subclass: 'fiend', description: 'When you reduce a hostile creature to 0 hit points, gain temporary hit points equal to your Charisma modifier + your warlock level.' },
      { level: 1, name: 'Expanded Spell List', subclass: 'fiend', description: 'Burning hands, command, blindness/deafness, scorching ray, fireball, stinking cloud, fire shield, wall of fire, flame strike, and hallow are added to your spell list.', modifiers: [{ type: 'expanded-list', spells: ['srd51:spell.burning-hands', 'srd51:spell.command', 'srd51:spell.scorching-ray', 'srd51:spell.fireball', 'srd51:spell.stinking-cloud', 'srd51:spell.fire-shield', 'srd51:spell.wall-of-fire', 'srd51:spell.flame-strike'] }] },
      { level: 2, name: 'Eldritch Invocations', description: 'Fragments of forbidden knowledge that grant abilities.', modifiers: [{ type: 'invocations', perLevel: [0, 0, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8] }] },
      { level: 3, name: 'Pact Boon', kind: 'choice', description: 'Choose Pact of the Chain, Pact of the Blade, or Pact of the Tome.', choiceOptions: ['Pact of the Chain', 'Pact of the Blade', 'Pact of the Tome'] },
      asi(4),
      { level: 6, name: "Dark One's Own Luck", subclass: 'fiend', description: 'Add 1d10 to an ability check or saving throw, once per short or long rest.' },
      asi(8),
      { level: 10, name: 'Fiendish Resilience', subclass: 'fiend', description: 'Choose one damage type after a rest to gain resistance to.' },
      { level: 11, name: 'Mystic Arcanum (6th level)', description: 'Choose one 6th-level spell you can cast once per long rest without a slot.', modifiers: [{ type: 'mystic-arcanum', spellLevel: 6 }] },
      asi(12),
      { level: 13, name: 'Mystic Arcanum (7th level)', description: 'Choose one 7th-level spell you can cast once per long rest without a slot.', modifiers: [{ type: 'mystic-arcanum', spellLevel: 7 }] },
      { level: 14, name: 'Hurl Through Hell', subclass: 'fiend', description: 'Send a creature you hit through the lower planes for 10d10 psychic damage, once per long rest.' },
      { level: 15, name: 'Mystic Arcanum (8th level)', description: 'Choose one 8th-level spell you can cast once per long rest without a slot.', modifiers: [{ type: 'mystic-arcanum', spellLevel: 8 }] },
      asi(16),
      { level: 17, name: 'Mystic Arcanum (9th level)', description: 'Choose one 9th-level spell you can cast once per long rest without a slot.', modifiers: [{ type: 'mystic-arcanum', spellLevel: 9 }] },
      asi(19),
      { level: 20, name: 'Eldritch Master', description: 'Regain all Pact Magic slots by entreating your patron, once per long rest.' },
    ],
  },

  {
    slug: 'wizard', name: 'Wizard', hitDie: 6,
    savingThrows: ['int', 'wis'],
    armorProficiencies: [],
    weaponProficiencies: ['srd51:weapon.dagger', 'srd51:weapon.dart', 'srd51:weapon.sling', 'srd51:weapon.quarterstaff', 'srd51:weapon.crossbow-light'],
    toolProficiencies: [],
    skillChoices: {
      count: 2,
      from: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion'].map((s) => `srd51:skill.${s}`),
    },
    asiLevels: [4, 8, 12, 16, 19],
    spellcasting: {
      progression: 'full', ability: 'int', prepares: true, ritual: true,
      listSlug: 'wizard', preparedFormula: 'ability+level', spellbook: true,
      cantripsKnown: CANTRIPS_3_4_5,
    },
    subclassLevel: 2, subclassLabel: 'Arcane Tradition',
    subclasses: [{ slug: 'evocation', name: 'School of Evocation' }],
    startingKit: { pack: 'srd51:gear.scholars-pack', extras: ['srd51:gear.spellbook', 'srd51:gear.arcane-focus'], focus: 'arcane' },
    tags: ['caster', 'arcane-caster', 'controller', 'artillery'],
    features: [
      { level: 1, name: 'Spellcasting', description: 'You cast wizard spells using Intelligence, preparing them from your spellbook after a long rest.' },
      { level: 1, name: 'Arcane Recovery', description: 'Recover expended spell slots with a combined level equal to half your wizard level, rounded up, once per day after a short rest.' },
      { level: 2, name: 'Evocation Savant', subclass: 'evocation', description: 'The gold and time to copy an evocation spell into your spellbook are halved.' },
      { level: 2, name: 'Sculpt Spells', subclass: 'evocation', description: 'Protect allies from your own evocation spells; they automatically succeed on the save and take no damage.' },
      asi(4),
      { level: 6, name: 'Potent Cantrip', subclass: 'evocation', description: 'Creatures that succeed on saves against your cantrips take half damage.' },
      asi(8),
      { level: 10, name: 'Empowered Evocation', subclass: 'evocation', description: 'Add your Intelligence modifier to one damage roll of any wizard evocation spell you cast.' },
      asi(12),
      { level: 14, name: 'Overchannel', subclass: 'evocation', description: 'Deal maximum damage with a wizard spell of 5th level or lower, at increasing cost to yourself after the first use.' },
      asi(16),
      { level: 18, name: 'Spell Mastery', description: 'Cast one 1st-level and one 2nd-level spell from your spellbook at will.' },
      asi(19),
      { level: 20, name: 'Signature Spells', description: 'Two 3rd-level spells are always prepared and can each be cast once per short rest without a slot.' },
    ],
  },
];
