// SRD 5.1 spells.
//
// Written as a compact table because the *shape* matters more than any single
// entry: `classes` is what makes a spell legal for a given caster, `level`
// gates it behind slots, and `tags` is what lets the spell builder pick a list
// that suits a role instead of picking at random. A controller warlock and a
// healer cleric draw from the same table through different tag weights.
//
// Class codes: b bard, c cleric, d druid, p paladin, r ranger, s sorcerer,
// k warlock, w wizard.

const CLASS_CODES = {
  b: 'bard', c: 'cleric', d: 'druid', p: 'paladin',
  r: 'ranger', s: 'sorcerer', k: 'warlock', w: 'wizard',
};

/** Expands one row of the table into a full spell entity. */
const S = (slug, name, level, school, codes, tags, o = {}) => ({
  slug,
  name,
  level,
  school,
  classes: [...codes].map((c) => CLASS_CODES[c]),
  tags: tags.split(' '),
  castingTime: o.t || '1 action',
  range: o.r || 'Self',
  duration: o.d || 'Instantaneous',
  components: o.c || 'V, S',
  concentration: !!o.conc,
  ritual: !!o.rit,
  description: o.x || '',
  ...(o.dmg ? { damage: o.dmg } : {}),
  ...(o.save ? { save: o.save } : {}),
  ...(o.heal ? { heal: o.heal } : {}),
});

const SPELLS_LOW = [
  // --- cantrips ---------------------------------------------------------------
  S('acid-splash', 'Acid Splash', 0, 'Conjuration', 'sw', 'damage', { r: '60 feet', save: 'dex', dmg: '1d6 acid', x: 'Hurl a bubble of acid at one creature, or two within 5 feet of each other. Dexterity save or take 1d6 acid damage. Scales at 5th, 11th, and 17th level.' }),
  S('chill-touch', 'Chill Touch', 0, 'Necromancy', 'ksw', 'damage control', { r: '120 feet', d: '1 round', dmg: '1d8 necrotic', x: 'Spectral hand attack. On a hit the target takes 1d8 necrotic damage and cannot regain hit points until your next turn. Undead also have disadvantage on attacks against you.' }),
  S('dancing-lights', 'Dancing Lights', 0, 'Evocation', 'bsw', 'utility', { r: '120 feet', d: '1 minute', c: 'V, S, M', conc: true, x: 'Create up to four torch-sized lights you can move as a bonus action.' }),
  S('druidcraft', 'Druidcraft', 0, 'Transmutation', 'd', 'utility', { r: '30 feet', x: 'Predict the weather, bloom a flower, light or snuff a small flame, or create a harmless sensory effect.' }),
  S('eldritch-blast', 'Eldritch Blast', 0, 'Evocation', 'k', 'damage', { r: '120 feet', dmg: '1d10 force', x: 'A beam of crackling energy. Ranged spell attack for 1d10 force damage. You create additional beams at 5th, 11th, and 17th level.' }),
  S('fire-bolt', 'Fire Bolt', 0, 'Evocation', 'sw', 'damage', { r: '120 feet', dmg: '1d10 fire', x: 'Ranged spell attack for 1d10 fire damage. Scales at 5th, 11th, and 17th level.' }),
  S('guidance', 'Guidance', 0, 'Divination', 'cd', 'support', { r: 'Touch', d: '1 minute', conc: true, x: 'The target can add 1d4 to one ability check of its choice before the spell ends.' }),
  S('light', 'Light', 0, 'Evocation', 'bcsw', 'utility', { r: 'Touch', d: '1 hour', c: 'V, M', x: 'An object sheds bright light in a 20-foot radius and dim light for 20 feet beyond.' }),
  S('mage-hand', 'Mage Hand', 0, 'Conjuration', 'bksw', 'utility', { r: '30 feet', d: '1 minute', x: 'A spectral hand that can manipulate objects of up to 10 pounds.' }),
  S('mending', 'Mending', 0, 'Transmutation', 'bcdsw', 'utility', { t: '1 minute', r: 'Touch', c: 'V, S, M', x: 'Repair a single break or tear in an object.' }),
  S('message', 'Message', 0, 'Transmutation', 'bsw', 'utility', { r: '120 feet', d: '1 round', c: 'V, S, M', x: 'Whisper a message that only the target can hear, and receive a whispered reply.' }),
  S('minor-illusion', 'Minor Illusion', 0, 'Illusion', 'bksw', 'utility social', { r: '30 feet', d: '1 minute', c: 'S, M', x: 'Create a sound or an image of an object no larger than a 5-foot cube.' }),
  S('poison-spray', 'Poison Spray', 0, 'Conjuration', 'dksw', 'damage', { r: '10 feet', save: 'con', dmg: '1d12 poison', x: 'Constitution save or take 1d12 poison damage. Scales at 5th, 11th, and 17th level.' }),
  S('prestidigitation', 'Prestidigitation', 0, 'Transmutation', 'bksw', 'utility social', { r: '10 feet', d: 'Up to 1 hour', x: 'A minor magical trick: a harmless sensory effect, a lit or snuffed flame, a cleaned or soiled object, a trinket.' }),
  S('produce-flame', 'Produce Flame', 0, 'Conjuration', 'd', 'damage utility', { d: '10 minutes', dmg: '1d8 fire', x: 'A flame in your hand sheds light and can be hurled as a ranged spell attack for 1d8 fire damage.' }),
  S('ray-of-frost', 'Ray of Frost', 0, 'Evocation', 'sw', 'damage control', { r: '60 feet', dmg: '1d8 cold', x: 'Ranged spell attack for 1d8 cold damage, and the target’s speed drops by 10 feet until your next turn.' }),
  S('resistance', 'Resistance', 0, 'Abjuration', 'cd', 'defense', { r: 'Touch', d: '1 minute', c: 'V, S, M', conc: true, x: 'The target can add 1d4 to one saving throw of its choice before the spell ends.' }),
  S('sacred-flame', 'Sacred Flame', 0, 'Evocation', 'c', 'damage', { r: '60 feet', save: 'dex', dmg: '2d8 radiant', x: 'Dexterity save (no cover benefit) or take 2d8 radiant damage. Scales at 5th, 11th, and 17th level.' }),
  S('shillelagh', 'Shillelagh', 0, 'Transmutation', 'd', 'damage support', { t: '1 bonus action', r: 'Touch', d: '1 minute', c: 'V, S, M', x: 'Your club or quarterstaff deals 1d8 damage and uses your spellcasting ability for attack and damage rolls.' }),
  S('shocking-grasp', 'Shocking Grasp', 0, 'Evocation', 'sw', 'damage control', { r: 'Touch', dmg: '1d8 lightning', x: 'Melee spell attack with advantage against a target wearing metal armor. On a hit it takes 1d8 lightning damage and cannot take reactions until its next turn.' }),
  S('spare-the-dying', 'Spare the Dying', 0, 'Necromancy', 'c', 'healing', { r: 'Touch', x: 'A creature at 0 hit points becomes stable.' }),
  S('thaumaturgy', 'Thaumaturgy', 0, 'Transmutation', 'c', 'social utility', { r: '30 feet', d: 'Up to 1 minute', c: 'V', x: 'A minor wonder: a booming voice, flickering flames, tremors, or doors flung open.' }),
  S('thorn-whip', 'Thorn Whip', 0, 'Transmutation', 'd', 'damage control', { r: '30 feet', c: 'V, S, M', dmg: '1d6 piercing', x: 'Melee spell attack for 1d6 piercing damage, pulling a Large or smaller creature 10 feet closer.' }),
  S('true-strike', 'True Strike', 0, 'Divination', 'bsw', 'utility', { r: '30 feet', d: '1 round', c: 'S', conc: true, x: 'Gain advantage on your first attack roll against the target on your next turn.' }),
  S('vicious-mockery', 'Vicious Mockery', 0, 'Enchantment', 'b', 'damage control', { r: '60 feet', c: 'V', save: 'wis', dmg: '1d4 psychic', x: 'Wisdom save or take 1d4 psychic damage and have disadvantage on its next attack roll.' }),

  // --- 1st level --------------------------------------------------------------
  S('alarm', 'Alarm', 1, 'Abjuration', 'rw', 'exploration defense', { t: '1 minute', r: '30 feet', d: '8 hours', c: 'V, S, M', rit: true, x: 'Set a mental or audible alarm on a 20-foot cube.' }),
  S('bane', 'Bane', 1, 'Enchantment', 'bc', 'control', { r: '30 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'cha', x: 'Up to three creatures subtract 1d4 from attack rolls and saving throws.' }),
  S('bless', 'Bless', 1, 'Enchantment', 'cp', 'support', { r: '30 feet', d: '1 minute', c: 'V, S, M', conc: true, x: 'Up to three creatures add 1d4 to attack rolls and saving throws.' }),
  S('burning-hands', 'Burning Hands', 1, 'Evocation', 'sw', 'damage', { r: 'Self (15-foot cone)', save: 'dex', dmg: '3d6 fire', x: 'Each creature in a 15-foot cone makes a Dexterity save, taking 3d6 fire damage on a failure and half on a success.' }),
  S('charm-person', 'Charm Person', 1, 'Enchantment', 'bdksw', 'social', { r: '30 feet', d: '1 hour', save: 'wis', x: 'Wisdom save or the target is charmed by you and regards you as a friendly acquaintance.' }),
  S('command', 'Command', 1, 'Enchantment', 'cp', 'control social', { r: '60 feet', d: '1 round', c: 'V', save: 'wis', x: 'Wisdom save or the target follows a one-word command on its next turn.' }),
  S('comprehend-languages', 'Comprehend Languages', 1, 'Divination', 'bksw', 'utility', { d: '1 hour', c: 'V, S, M', rit: true, x: 'Understand the literal meaning of any spoken or written language you hear or touch.' }),
  S('create-or-destroy-water', 'Create or Destroy Water', 1, 'Transmutation', 'cd', 'utility', { r: '30 feet', c: 'V, S, M', x: 'Create or destroy up to 10 gallons of water, or a brief rainfall in a 30-foot cube.' }),
  S('cure-wounds', 'Cure Wounds', 1, 'Evocation', 'bcdpr', 'healing', { r: 'Touch', heal: '1d8 + ability', x: 'A creature you touch regains 1d8 + your spellcasting ability modifier hit points, plus 1d8 per slot level above 1st.' }),
  S('detect-magic', 'Detect Magic', 1, 'Divination', 'bcdprsw', 'utility exploration', { d: '10 minutes', conc: true, rit: true, x: 'Sense the presence of magic within 30 feet, and identify its school with an action.' }),
  S('disguise-self', 'Disguise Self', 1, 'Illusion', 'bsw', 'social', { d: '1 hour', x: 'Change your appearance, including clothing and equipment, until the spell ends.' }),
  S('divine-favor', 'Divine Favor', 1, 'Evocation', 'p', 'damage', { t: '1 bonus action', d: '1 minute', conc: true, dmg: '1d4 radiant', x: 'Your weapon attacks deal an extra 1d4 radiant damage on a hit.' }),
  S('entangle', 'Entangle', 1, 'Conjuration', 'd', 'control', { r: '90 feet', d: '1 minute', conc: true, save: 'str', x: 'Grasping weeds fill a 20-foot square; creatures failing a Strength save are restrained.' }),
  S('expeditious-retreat', 'Expeditious Retreat', 1, 'Transmutation', 'ksw', 'mobility', { t: '1 bonus action', d: '10 minutes', conc: true, x: 'Take the Dash action as a bonus action on each of your turns.' }),
  S('faerie-fire', 'Faerie Fire', 1, 'Evocation', 'bd', 'control', { r: '60 feet', d: '1 minute', c: 'V', conc: true, save: 'dex', x: 'Objects and creatures in a 20-foot cube are outlined in light; attacks against them have advantage.' }),
  S('false-life', 'False Life', 1, 'Necromancy', 'sw', 'defense', { c: 'V, S, M', x: 'Gain 1d4 + 4 temporary hit points, plus 5 per slot level above 1st.' }),
  S('feather-fall', 'Feather Fall', 1, 'Transmutation', 'bsw', 'mobility', { t: '1 reaction', r: '60 feet', d: '1 minute', c: 'V, M', x: 'Up to five falling creatures descend 60 feet per round and take no falling damage.' }),
  S('find-familiar', 'Find Familiar', 1, 'Conjuration', 'w', 'utility', { t: '1 hour', r: '10 feet', c: 'V, S, M', rit: true, x: 'Gain a spirit familiar in animal form that can scout, deliver touch spells, and grants you advantage on attacks near it.' }),
  S('fog-cloud', 'Fog Cloud', 1, 'Conjuration', 'drsw', 'control', { r: '120 feet', d: '1 hour', c: 'V, S', conc: true, x: 'A 20-foot-radius sphere of fog heavily obscures its area.' }),
  S('goodberry', 'Goodberry', 1, 'Transmutation', 'dr', 'healing', { c: 'V, S, M', heal: '1', x: 'Create up to ten berries; eating one restores 1 hit point and sustains a creature for a day.' }),
  S('grease', 'Grease', 1, 'Conjuration', 'w', 'control', { r: '60 feet', d: '1 minute', c: 'V, S, M', save: 'dex', x: 'A 10-foot square becomes difficult terrain; creatures failing a Dexterity save fall prone.' }),
  S('guiding-bolt', 'Guiding Bolt', 1, 'Evocation', 'c', 'damage', { r: '120 feet', d: '1 round', dmg: '4d6 radiant', x: 'Ranged spell attack for 4d6 radiant damage; the next attack against the target has advantage.' }),
  S('healing-word', 'Healing Word', 1, 'Evocation', 'bcd', 'healing', { t: '1 bonus action', r: '60 feet', c: 'V', heal: '1d4 + ability', x: 'A creature you can see regains 1d4 + your spellcasting ability modifier hit points.' }),
  S('hellish-rebuke', 'Hellish Rebuke', 1, 'Evocation', 'k', 'damage', { t: '1 reaction', r: '60 feet', save: 'dex', dmg: '2d10 fire', x: 'In response to being damaged, the attacker makes a Dexterity save, taking 2d10 fire damage on a failure and half on a success.' }),
  S('heroism', 'Heroism', 1, 'Enchantment', 'bp', 'support defense', { r: 'Touch', d: '1 minute', conc: true, x: 'The target is immune to being frightened and gains temporary hit points equal to your spellcasting ability modifier each turn.' }),
  S('hex', 'Hex', 1, 'Enchantment', 'k', 'damage', { t: '1 bonus action', r: '90 feet', d: '1 hour', c: 'V, S, M', conc: true, dmg: '1d6 necrotic', x: 'Your attacks against the target deal an extra 1d6 necrotic damage, and it has disadvantage on checks with one ability.' }),
  S('hunters-mark', "Hunter's Mark", 1, 'Divination', 'r', 'damage', { t: '1 bonus action', r: '90 feet', d: '1 hour', c: 'V', conc: true, dmg: '1d6', x: 'Your weapon attacks against the marked target deal an extra 1d6 damage, and you have advantage to track it.' }),
  S('identify', 'Identify', 1, 'Divination', 'bw', 'utility', { t: '1 minute', r: 'Touch', c: 'V, S, M', rit: true, x: 'Learn an item’s properties and any spells affecting a creature.' }),
  S('inflict-wounds', 'Inflict Wounds', 1, 'Necromancy', 'c', 'damage', { r: 'Touch', dmg: '3d10 necrotic', x: 'Melee spell attack for 3d10 necrotic damage, plus 1d10 per slot level above 1st.' }),
  S('jump', 'Jump', 1, 'Transmutation', 'drsw', 'mobility', { r: 'Touch', d: '1 minute', c: 'V, S, M', x: 'The target’s jump distance is tripled.' }),
  S('longstrider', 'Longstrider', 1, 'Transmutation', 'bdrw', 'mobility', { r: 'Touch', d: '1 hour', c: 'V, S, M', x: 'The target’s speed increases by 10 feet.' }),
  S('mage-armor', 'Mage Armor', 1, 'Abjuration', 'sw', 'defense', { r: 'Touch', d: '8 hours', c: 'V, S, M', x: 'An unarmored creature’s base AC becomes 13 + its Dexterity modifier.' }),
  S('magic-missile', 'Magic Missile', 1, 'Evocation', 'sw', 'damage', { r: '120 feet', dmg: '3d4+3 force', x: 'Three darts each strike a target automatically for 1d4 + 1 force damage. One extra dart per slot level above 1st.' }),
  S('protection-from-evil-and-good', 'Protection from Evil and Good', 1, 'Abjuration', 'ckpw', 'defense', { r: 'Touch', d: '10 minutes', c: 'V, S, M', conc: true, x: 'Aberrations, celestials, elementals, fey, fiends, and undead have disadvantage on attacks against the target, which also cannot be charmed, frightened, or possessed by them.' }),
  S('purify-food-and-drink', 'Purify Food and Drink', 1, 'Transmutation', 'cdp', 'utility', { r: '10 feet', rit: true, x: 'Food and drink in a 5-foot-radius sphere are purified of poison and disease.' }),
  S('sanctuary', 'Sanctuary', 1, 'Abjuration', 'c', 'defense', { t: '1 bonus action', r: '30 feet', d: '1 minute', c: 'V, S, M', save: 'wis', x: 'A creature attacking the warded target must first make a Wisdom save or choose a new target.' }),
  S('shield', 'Shield', 1, 'Abjuration', 'sw', 'defense', { t: '1 reaction', d: '1 round', x: 'Gain +5 AC until the start of your next turn, including against the triggering attack, and take no damage from magic missile.' }),
  S('shield-of-faith', 'Shield of Faith', 1, 'Abjuration', 'cp', 'defense', { t: '1 bonus action', r: '60 feet', d: '10 minutes', c: 'V, S, M', conc: true, x: 'A creature gains +2 AC.' }),
  S('silent-image', 'Silent Image', 1, 'Illusion', 'bsw', 'control social', { r: '60 feet', d: '10 minutes', c: 'V, S, M', conc: true, x: 'Create a purely visual illusion no larger than a 15-foot cube.' }),
  S('sleep', 'Sleep', 1, 'Enchantment', 'bsw', 'control', { r: '90 feet', d: '1 minute', c: 'V, S, M', x: 'Roll 5d8; creatures in a 20-foot radius fall unconscious in ascending order of current hit points until the total is spent.' }),
  S('speak-with-animals', 'Speak with Animals', 1, 'Divination', 'bdr', 'exploration social', { d: '10 minutes', rit: true, x: 'Comprehend and verbally communicate with beasts.' }),
  S('thunderwave', 'Thunderwave', 1, 'Evocation', 'bdsw', 'damage control', { r: 'Self (15-foot cube)', save: 'con', dmg: '2d8 thunder', x: 'Creatures in a 15-foot cube make a Constitution save, taking 2d8 thunder damage and being pushed 10 feet on a failure.' }),
  S('unseen-servant', 'Unseen Servant', 1, 'Conjuration', 'bkw', 'utility', { r: '60 feet', d: '1 hour', c: 'V, S, M', rit: true, x: 'An invisible force performs simple tasks at your command.' }),
];

const SPELLS_MID = [
  // --- 2nd level --------------------------------------------------------------
  S('aid', 'Aid', 2, 'Abjuration', 'cp', 'healing support', { r: '30 feet', d: '8 hours', c: 'V, S, M', heal: '5', x: 'Three creatures gain 5 temporary hit points and 5 to their hit point maximum, plus 5 more per slot level above 2nd.' }),
  S('animal-messenger', 'Animal Messenger', 2, 'Enchantment', 'bdr', 'utility', { r: '30 feet', d: '24 hours', c: 'V, S, M', rit: true, x: 'A Tiny beast carries a message to a place you describe.' }),
  S('augury', 'Augury', 2, 'Divination', 'c', 'exploration', { t: '1 minute', c: 'V, S, M', rit: true, x: 'Learn whether a course of action in the next 30 minutes will bring weal, woe, both, or nothing.' }),
  S('barkskin', 'Barkskin', 2, 'Transmutation', 'dr', 'defense', { r: 'Touch', d: '1 hour', c: 'V, S, M', conc: true, x: 'The target’s AC cannot be lower than 16.' }),
  S('blindness-deafness', 'Blindness/Deafness', 2, 'Necromancy', 'bcsw', 'control', { r: '30 feet', d: '1 minute', c: 'V', save: 'con', x: 'Constitution save or the target is blinded or deafened for the duration.' }),
  S('blur', 'Blur', 2, 'Illusion', 'sw', 'defense', { d: '1 minute', c: 'V', conc: true, x: 'Attack rolls against you have disadvantage unless the attacker does not rely on sight.' }),
  S('calm-emotions', 'Calm Emotions', 2, 'Enchantment', 'bc', 'control social', { r: '60 feet', d: '1 minute', conc: true, save: 'cha', x: 'Suppress charm and fear effects, or make creatures indifferent, in a 20-foot-radius sphere.' }),
  S('darkness', 'Darkness', 2, 'Evocation', 'ksw', 'control', { r: '60 feet', d: '10 minutes', c: 'V, M', conc: true, x: 'Magical darkness fills a 15-foot-radius sphere that even darkvision cannot see through.' }),
  S('darkvision', 'Darkvision', 2, 'Transmutation', 'drsw', 'utility', { r: 'Touch', d: '8 hours', c: 'V, S, M', x: 'The target gains darkvision out to 60 feet.' }),
  S('detect-thoughts', 'Detect Thoughts', 2, 'Divination', 'bsw', 'social exploration', { r: 'Self', d: '1 minute', c: 'V, S, M', conc: true, x: 'Read the surface thoughts of creatures within 30 feet, and probe deeper against a Wisdom save.' }),
  S('enhance-ability', 'Enhance Ability', 2, 'Transmutation', 'bcds', 'support', { r: 'Touch', d: '1 hour', c: 'V, S, M', conc: true, x: 'The target gains advantage on checks with one ability, plus a rider depending on the ability chosen.' }),
  S('enlarge-reduce', 'Enlarge/Reduce', 2, 'Transmutation', 'sw', 'control support', { r: '30 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'con', x: 'Double or halve the target’s size, adjusting its damage by 1d4 and its Strength checks accordingly.' }),
  S('find-traps', 'Find Traps', 2, 'Divination', 'cdr', 'exploration', { r: '120 feet', x: 'Sense the presence of any trap within range that is within line of sight.' }),
  S('flaming-sphere', 'Flaming Sphere', 2, 'Conjuration', 'dw', 'damage control', { r: '60 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'dex', dmg: '2d6 fire', x: 'A 5-foot sphere of fire you move 30 feet as a bonus action; creatures ending their turn near it make a Dexterity save against 2d6 fire damage.' }),
  S('gust-of-wind', 'Gust of Wind', 2, 'Evocation', 'dsw', 'control', { r: 'Self (60-foot line)', d: '1 minute', c: 'V, S, M', conc: true, save: 'str', x: 'A line of strong wind pushes creatures 15 feet away and makes movement into it cost double.' }),
  S('heat-metal', 'Heat Metal', 2, 'Transmutation', 'bd', 'damage control', { r: '60 feet', d: '1 minute', c: 'V, S, M', conc: true, dmg: '2d8 fire', x: 'A metal object glows red hot, dealing 2d8 fire damage and forcing a Constitution save to avoid dropping it.' }),
  S('hold-person', 'Hold Person', 2, 'Enchantment', 'bcdksw', 'control', { r: '60 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'wis', x: 'A humanoid is paralysed on a failed Wisdom save, repeating the save at the end of each of its turns.' }),
  S('invisibility', 'Invisibility', 2, 'Illusion', 'bksw', 'mobility defense', { r: 'Touch', d: '1 hour', c: 'V, S, M', conc: true, x: 'The target becomes invisible until it attacks or casts a spell.' }),
  S('knock', 'Knock', 2, 'Transmutation', 'bsw', 'utility', { r: '60 feet', c: 'V', x: 'Unlock one locked, stuck, or barred object, with a loud knock audible 300 feet away.' }),
  S('lesser-restoration', 'Lesser Restoration', 2, 'Abjuration', 'bcdpr', 'healing', { r: 'Touch', x: 'End one disease or the blinded, deafened, paralysed, or poisoned condition.' }),
  S('levitate', 'Levitate', 2, 'Transmutation', 'sw', 'mobility', { r: '60 feet', d: '10 minutes', c: 'V, S, M', conc: true, save: 'con', x: 'A creature or object rises up to 20 feet and remains suspended.' }),
  S('magic-weapon', 'Magic Weapon', 2, 'Transmutation', 'pw', 'support', { t: '1 bonus action', r: 'Touch', d: '1 hour', conc: true, x: 'A nonmagical weapon becomes magical with a +1 bonus, rising with slot level.' }),
  S('mirror-image', 'Mirror Image', 2, 'Illusion', 'ksw', 'defense', { d: '1 minute', x: 'Three illusory duplicates that may absorb attacks aimed at you.' }),
  S('misty-step', 'Misty Step', 2, 'Conjuration', 'ksw', 'mobility', { t: '1 bonus action', c: 'V', x: 'Teleport up to 30 feet to an unoccupied space you can see.' }),
  S('moonbeam', 'Moonbeam', 2, 'Evocation', 'd', 'damage control', { r: '120 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'con', dmg: '2d10 radiant', x: 'A 5-foot-radius beam of moonlight you move 60 feet each turn; creatures in it make a Constitution save against 2d10 radiant damage.' }),
  S('pass-without-trace', 'Pass without Trace', 2, 'Abjuration', 'dr', 'exploration', { d: '1 hour', c: 'V, S, M', conc: true, x: 'You and companions within 30 feet gain +10 to Stealth checks and cannot be tracked.' }),
  S('prayer-of-healing', 'Prayer of Healing', 2, 'Evocation', 'c', 'healing', { t: '10 minutes', r: '30 feet', c: 'V', heal: '2d8 + ability', x: 'Up to six creatures each regain 2d8 + your spellcasting ability modifier hit points.' }),
  S('ray-of-enfeeblement', 'Ray of Enfeeblement', 2, 'Necromancy', 'kw', 'control', { r: '60 feet', d: '1 minute', conc: true, x: 'On a hit with a ranged spell attack, the target deals half damage with Strength-based weapon attacks.' }),
  S('scorching-ray', 'Scorching Ray', 2, 'Evocation', 'sw', 'damage', { r: '120 feet', dmg: '6d6 fire', x: 'Three rays, each a ranged spell attack for 2d6 fire damage. One extra ray per slot level above 2nd.' }),
  S('see-invisibility', 'See Invisibility', 2, 'Divination', 'bsw', 'utility', { d: '1 hour', c: 'V, S, M', x: 'See invisible creatures and objects, and into the Ethereal Plane.' }),
  S('shatter', 'Shatter', 2, 'Evocation', 'bksw', 'damage', { r: '60 feet', c: 'V, S, M', save: 'con', dmg: '3d8 thunder', x: 'A 10-foot-radius sphere of ringing noise; Constitution save or take 3d8 thunder damage.' }),
  S('silence', 'Silence', 2, 'Illusion', 'bcr', 'control', { r: '120 feet', d: '10 minutes', conc: true, rit: true, x: 'No sound can be created within or pass through a 20-foot-radius sphere; verbal components fail inside it.' }),
  S('spider-climb', 'Spider Climb', 2, 'Transmutation', 'ksw', 'mobility', { r: 'Touch', d: '1 hour', c: 'V, S, M', conc: true, x: 'The target can climb walls and ceilings, gaining a climbing speed equal to its walking speed.' }),
  S('spike-growth', 'Spike Growth', 2, 'Transmutation', 'dr', 'control damage', { r: '150 feet', d: '10 minutes', c: 'V, S, M', conc: true, dmg: '2d4 piercing', x: 'A 20-foot radius becomes difficult terrain dealing 2d4 piercing damage per 5 feet of movement.' }),
  S('spiritual-weapon', 'Spiritual Weapon', 2, 'Evocation', 'c', 'damage', { t: '1 bonus action', r: '60 feet', d: '1 minute', c: 'V, S', dmg: '1d8 force + ability', x: 'A floating spectral weapon makes a melee spell attack for 1d8 + your spellcasting ability modifier force damage as a bonus action.' }),
  S('suggestion', 'Suggestion', 2, 'Enchantment', 'bksw', 'social control', { r: '30 feet', d: '8 hours', c: 'V, M', conc: true, save: 'wis', x: 'Suggest a reasonable course of action; on a failed Wisdom save the target pursues it.' }),
  S('web', 'Web', 2, 'Conjuration', 'sw', 'control', { r: '60 feet', d: '1 hour', c: 'V, S, M', conc: true, save: 'dex', x: 'Thick webs fill a 20-foot cube as difficult terrain; creatures failing a Dexterity save are restrained.' }),
  S('zone-of-truth', 'Zone of Truth', 2, 'Enchantment', 'bcp', 'social', { r: '60 feet', d: '10 minutes', save: 'cha', x: 'Creatures in a 15-foot-radius sphere cannot speak a deliberate lie.' }),

  // --- 3rd level --------------------------------------------------------------
  S('animate-dead', 'Animate Dead', 3, 'Necromancy', 'cw', 'utility', { t: '1 minute', r: '10 feet', d: 'Instantaneous', c: 'V, S, M', x: 'Raise a skeleton or zombie from a corpse, under your command for 24 hours.' }),
  S('beacon-of-hope', 'Beacon of Hope', 3, 'Abjuration', 'c', 'support healing', { r: '30 feet', d: '1 minute', conc: true, x: 'Targets have advantage on Wisdom and death saves, and regain the maximum from healing.' }),
  S('bestow-curse', 'Bestow Curse', 3, 'Necromancy', 'bcw', 'control', { r: 'Touch', d: '1 minute', conc: true, save: 'wis', x: 'Curse a creature with disadvantage on one ability, wasted turns, extra necrotic damage, or a lost action.' }),
  S('blink', 'Blink', 3, 'Transmutation', 'sw', 'defense mobility', { d: '1 minute', x: 'Roll a d20 at the end of each turn; on an 11 or higher you vanish to the Ethereal Plane until your next turn.' }),
  S('call-lightning', 'Call Lightning', 3, 'Conjuration', 'd', 'damage', { r: '120 feet', d: '10 minutes', conc: true, save: 'dex', dmg: '3d10 lightning', x: 'A storm cloud from which you call a bolt each turn; Dexterity save or take 3d10 lightning damage.' }),
  S('clairvoyance', 'Clairvoyance', 3, 'Divination', 'bcsw', 'exploration', { t: '10 minutes', r: '1 mile', d: '10 minutes', c: 'V, S, M', conc: true, x: 'Create an invisible sensor you can see or hear through.' }),
  S('counterspell', 'Counterspell', 3, 'Abjuration', 'ksw', 'defense', { t: '1 reaction', r: '60 feet', c: 'S', x: 'Interrupt a spell of 3rd level or lower automatically, or higher with an ability check.' }),
  S('create-food-and-water', 'Create Food and Water', 3, 'Conjuration', 'cp', 'utility', { r: '30 feet', x: 'Create 45 pounds of food and 30 gallons of water.' }),
  S('daylight', 'Daylight', 3, 'Evocation', 'cdprs', 'utility', { r: '60 feet', d: '1 hour', x: 'A 60-foot-radius sphere of bright light that dispels lesser magical darkness.' }),
  S('dispel-magic', 'Dispel Magic', 3, 'Abjuration', 'bcdkpsw', 'utility defense', { r: '120 feet', x: 'End spells of 3rd level or lower on a target automatically, or higher with an ability check.' }),
  S('fear', 'Fear', 3, 'Illusion', 'bksw', 'control', { r: 'Self (30-foot cone)', d: '1 minute', c: 'V, S, M', conc: true, save: 'wis', x: 'Creatures in a cone drop what they hold and are frightened, using their turns to flee.' }),
  S('fireball', 'Fireball', 3, 'Evocation', 'sw', 'damage', { r: '150 feet', c: 'V, S, M', save: 'dex', dmg: '8d6 fire', x: 'A 20-foot-radius sphere of flame; Dexterity save for 8d6 fire damage, half on a success. +1d6 per slot level above 3rd.' }),
  S('fly', 'Fly', 3, 'Transmutation', 'ksw', 'mobility', { r: 'Touch', d: '10 minutes', c: 'V, S, M', conc: true, x: 'The target gains a flying speed of 60 feet.' }),
  S('haste', 'Haste', 3, 'Transmutation', 'sw', 'support', { r: '30 feet', d: '1 minute', c: 'V, S, M', conc: true, x: 'The target’s speed doubles, it gains +2 AC and advantage on Dexterity saves, and an additional limited action each turn.' }),
  S('hypnotic-pattern', 'Hypnotic Pattern', 3, 'Illusion', 'bksw', 'control', { r: '120 feet', d: '1 minute', c: 'S, M', conc: true, save: 'wis', x: 'A twisting pattern in a 30-foot cube charms and incapacitates creatures that fail a Wisdom save.' }),
  S('lightning-bolt', 'Lightning Bolt', 3, 'Evocation', 'sw', 'damage', { r: 'Self (100-foot line)', c: 'V, S, M', save: 'dex', dmg: '8d6 lightning', x: 'A 100-foot line; Dexterity save for 8d6 lightning damage, half on a success.' }),
  S('major-image', 'Major Image', 3, 'Illusion', 'bksw', 'control social', { r: '120 feet', d: '10 minutes', c: 'V, S, M', conc: true, x: 'An illusion with sound, smell, and temperature, no larger than a 20-foot cube.' }),
  S('mass-healing-word', 'Mass Healing Word', 3, 'Evocation', 'c', 'healing', { t: '1 bonus action', r: '60 feet', c: 'V', heal: '1d4 + ability', x: 'Up to six creatures each regain 1d4 + your spellcasting ability modifier hit points.' }),
  S('nondetection', 'Nondetection', 3, 'Abjuration', 'brw', 'defense', { r: 'Touch', d: '8 hours', c: 'V, S, M', x: 'Hide a target from divination magic.' }),
  S('plant-growth', 'Plant Growth', 3, 'Transmutation', 'bdr', 'control', { r: '150 feet', x: 'Enrich plants over half a mile, or make a 100-foot radius difficult terrain.' }),
  S('protection-from-energy', 'Protection from Energy', 3, 'Abjuration', 'cdrsw', 'defense', { r: 'Touch', d: '1 hour', conc: true, x: 'The target gains resistance to one damage type of acid, cold, fire, lightning, or thunder.' }),
  S('remove-curse', 'Remove Curse', 3, 'Abjuration', 'ckpw', 'utility', { r: 'Touch', x: 'End all curses affecting one creature or object.' }),
  S('revivify', 'Revivify', 3, 'Necromancy', 'cp', 'healing', { r: 'Touch', c: 'V, S, M', x: 'Return a creature that died within the last minute to life with 1 hit point.' }),
  S('sending', 'Sending', 3, 'Evocation', 'bcw', 'utility', { r: 'Unlimited', c: 'V, S, M', x: 'Send a message of 25 words or fewer to a creature you are familiar with, anywhere.' }),
  S('sleet-storm', 'Sleet Storm', 3, 'Conjuration', 'dsw', 'control', { r: '150 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'dex', x: 'Freezing rain douses flames, obscures a 40-foot-radius cylinder, and knocks creatures prone.' }),
  S('slow', 'Slow', 3, 'Transmutation', 'sw', 'control', { r: '120 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'wis', x: 'Up to six creatures have their speed halved, -2 to AC and Dexterity saves, and lose reactions.' }),
  S('speak-with-dead', 'Speak with Dead', 3, 'Necromancy', 'bc', 'exploration social', { r: '10 feet', d: '10 minutes', c: 'V, S, M', x: 'Ask a corpse five questions.' }),
  S('spirit-guardians', 'Spirit Guardians', 3, 'Conjuration', 'c', 'damage control', { r: 'Self (15-foot radius)', d: '10 minutes', c: 'V, S, M', conc: true, save: 'wis', dmg: '3d8 radiant', x: 'Spirits flit around you; creatures in a 15-foot radius have their speed halved and take 3d8 radiant or necrotic damage on a failed Wisdom save.' }),
  S('stinking-cloud', 'Stinking Cloud', 3, 'Conjuration', 'bksw', 'control', { r: '90 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'con', x: 'A 20-foot-radius sphere of nauseating gas; creatures failing a Constitution save waste their action retching.' }),
  S('tongues', 'Tongues', 3, 'Divination', 'bcksw', 'utility social', { r: 'Touch', d: '1 hour', c: 'V, M', x: 'The target understands any spoken language and is understood by anyone who knows a language.' }),
  S('vampiric-touch', 'Vampiric Touch', 3, 'Necromancy', 'kw', 'damage healing', { d: '1 minute', conc: true, dmg: '3d6 necrotic', x: 'Melee spell attack for 3d6 necrotic damage; you regain half the damage dealt.' }),
  S('water-breathing', 'Water Breathing', 3, 'Transmutation', 'drsw', 'utility', { r: '30 feet', d: '24 hours', c: 'V, S, M', rit: true, x: 'Up to ten creatures can breathe underwater.' }),
  S('wind-wall', 'Wind Wall', 3, 'Evocation', 'dr', 'control defense', { r: '120 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'str', dmg: '3d8 bludgeoning', x: 'A wall of strong wind 50 feet long deflects arrows and small creatures.' }),
];

const SPELLS_HIGH = [
  // --- 4th level --------------------------------------------------------------
  S('banishment', 'Banishment', 4, 'Abjuration', 'ckpsw', 'control', { r: '60 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'cha', x: 'Send a creature to a harmless demiplane on a failed Charisma save.' }),
  S('blight', 'Blight', 4, 'Necromancy', 'dksw', 'damage', { r: '30 feet', save: 'con', dmg: '8d8 necrotic', x: 'Constitution save or take 8d8 necrotic damage; plants automatically fail.' }),
  S('confusion', 'Confusion', 4, 'Enchantment', 'bdsw', 'control', { r: '90 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'wis', x: 'Creatures in a 10-foot radius behave erratically, wandering or attacking at random.' }),
  S('death-ward', 'Death Ward', 4, 'Abjuration', 'cp', 'defense', { r: 'Touch', d: '8 hours', x: 'The first time the target would drop to 0 hit points, it drops to 1 instead.' }),
  S('dimension-door', 'Dimension Door', 4, 'Conjuration', 'bksw', 'mobility', { r: '500 feet', c: 'V', x: 'Teleport yourself and one willing creature up to 500 feet.' }),
  S('divination', 'Divination', 4, 'Divination', 'c', 'exploration', { t: '1 action', c: 'V, S, M', rit: true, x: 'Receive a truthful reply about a goal or event within seven days.' }),
  S('dominate-beast', 'Dominate Beast', 4, 'Enchantment', 'ds', 'control', { r: '60 feet', d: '1 minute', conc: true, save: 'wis', x: 'Charm a beast and issue it commands.' }),
  S('fire-shield', 'Fire Shield', 4, 'Evocation', 'w', 'defense damage', { d: '10 minutes', c: 'V, S, M', dmg: '2d8 fire', x: 'Flames wreath you, granting resistance to cold or fire and dealing 2d8 damage to creatures that hit you in melee.' }),
  S('freedom-of-movement', 'Freedom of Movement', 4, 'Abjuration', 'bcdr', 'mobility', { r: 'Touch', d: '1 hour', c: 'V, S, M', x: 'The target ignores difficult terrain and cannot be paralysed or restrained by magic.' }),
  S('greater-invisibility', 'Greater Invisibility', 4, 'Illusion', 'bsw', 'mobility defense', { r: 'Touch', d: '1 minute', conc: true, x: 'The target is invisible even while attacking or casting.' }),
  S('guardian-of-faith', 'Guardian of Faith', 4, 'Conjuration', 'c', 'defense damage', { r: '30 feet', d: '8 hours', c: 'V', save: 'dex', dmg: '20 radiant', x: 'A spectral guardian deals 20 radiant damage to hostile creatures that approach, up to 60 total.' }),
  S('hallucinatory-terrain', 'Hallucinatory Terrain', 4, 'Illusion', 'bdw', 'control', { t: '10 minutes', r: '300 feet', d: '24 hours', c: 'V, S, M', x: 'Disguise natural terrain in a 150-foot cube.' }),
  S('ice-storm', 'Ice Storm', 4, 'Evocation', 'dsw', 'damage control', { r: '300 feet', c: 'V, S, M', save: 'dex', dmg: '4d6 bludgeoning + 2d8 cold', x: 'Hail pounds a 20-foot-radius cylinder for 2d8 bludgeoning and 4d6 cold damage, leaving difficult terrain.' }),
  S('polymorph', 'Polymorph', 4, 'Transmutation', 'bdsw', 'control', { r: '60 feet', d: '1 hour', c: 'V, S, M', conc: true, save: 'wis', x: 'Transform a creature into a beast of CR equal to or less than its own.' }),
  S('stone-shape', 'Stone Shape', 4, 'Transmutation', 'cdw', 'utility', { r: 'Touch', c: 'V, S, M', x: 'Reshape a Medium-or-smaller section of stone into any form.' }),
  S('stoneskin', 'Stoneskin', 4, 'Abjuration', 'drsw', 'defense', { r: 'Touch', d: '1 hour', c: 'V, S, M', conc: true, x: 'The target has resistance to nonmagical bludgeoning, piercing, and slashing damage.' }),
  S('wall-of-fire', 'Wall of Fire', 4, 'Evocation', 'dsw', 'damage control', { r: '120 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'dex', dmg: '5d8 fire', x: 'A wall of flame 60 feet long deals 5d8 fire damage to creatures on its hot side.' }),

  // --- 5th level --------------------------------------------------------------
  S('animate-objects', 'Animate Objects', 5, 'Transmutation', 'bsw', 'damage', { r: '120 feet', d: '1 minute', conc: true, x: 'Up to ten objects come to life and fight for you.' }),
  S('antilife-shell', 'Antilife Shell', 5, 'Abjuration', 'd', 'defense', { r: 'Self (10-foot radius)', d: '1 hour', conc: true, x: 'A barrier that living creatures cannot pass.' }),
  S('cloudkill', 'Cloudkill', 5, 'Conjuration', 'sw', 'damage control', { r: '120 feet', d: '10 minutes', conc: true, save: 'con', dmg: '5d8 poison', x: 'A 20-foot-radius fog deals 5d8 poison damage and moves 10 feet away from you each round.' }),
  S('commune', 'Commune', 5, 'Divination', 'c', 'exploration', { t: '1 minute', d: '1 minute', c: 'V, S, M', rit: true, x: 'Ask your deity three yes-or-no questions.' }),
  S('cone-of-cold', 'Cone of Cold', 5, 'Evocation', 'sw', 'damage', { r: 'Self (60-foot cone)', c: 'V, S, M', save: 'con', dmg: '8d8 cold', x: 'A 60-foot cone; Constitution save for 8d8 cold damage, half on a success.' }),
  S('contagion', 'Contagion', 5, 'Necromancy', 'cd', 'damage control', { r: 'Touch', d: '7 days', save: 'con', x: 'A melee spell attack inflicts a disease that poisons the target and worsens over three failed saves.' }),
  S('dispel-evil-and-good', 'Dispel Evil and Good', 5, 'Abjuration', 'cp', 'defense', { d: '1 minute', c: 'V, S, M', conc: true, x: 'Celestials, elementals, fey, fiends, and undead have disadvantage on attacks against you, and you can dismiss or break their hold.' }),
  S('dominate-person', 'Dominate Person', 5, 'Enchantment', 'bsw', 'control', { r: '60 feet', d: '1 minute', conc: true, save: 'wis', x: 'Charm a humanoid and issue it commands.' }),
  S('dream', 'Dream', 5, 'Illusion', 'bkw', 'social', { t: '1 minute', r: 'Special', d: '8 hours', c: 'V, S, M', x: 'Shape the dreams of a sleeping creature, possibly denying it rest.' }),
  S('flame-strike', 'Flame Strike', 5, 'Evocation', 'c', 'damage', { r: '60 feet', c: 'V, S, M', save: 'dex', dmg: '4d6 fire + 4d6 radiant', x: 'A column of fire in a 10-foot-radius cylinder deals 4d6 fire and 4d6 radiant damage on a failed Dexterity save.' }),
  S('geas', 'Geas', 5, 'Enchantment', 'bcdpw', 'social control', { t: '1 minute', r: '60 feet', d: '30 days', c: 'V', save: 'wis', x: 'Command a creature to carry out a service, damaging it if it disobeys.' }),
  S('greater-restoration', 'Greater Restoration', 5, 'Abjuration', 'bcd', 'healing', { r: 'Touch', c: 'V, S, M', x: 'End one charm, petrification, curse, ability reduction, or hit point maximum reduction.' }),
  S('hallow', 'Hallow', 5, 'Evocation', 'c', 'defense', { t: '24 hours', r: 'Touch', d: 'Until dispelled', c: 'V, S, M', x: 'Imbue an area up to 60 feet with a warding effect against certain creature types.' }),
  S('hold-monster', 'Hold Monster', 5, 'Enchantment', 'bksw', 'control', { r: '90 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'wis', x: 'Paralyse any creature that is not undead on a failed Wisdom save.' }),
  S('insect-plague', 'Insect Plague', 5, 'Conjuration', 'cds', 'damage control', { r: '300 feet', d: '10 minutes', c: 'V, S, M', conc: true, save: 'con', dmg: '4d10 piercing', x: 'A 20-foot-radius swarm of locusts deals 4d10 piercing damage and creates difficult terrain.' }),
  S('legend-lore', 'Legend Lore', 5, 'Divination', 'bcw', 'exploration', { t: '10 minutes', c: 'V, S, M', x: 'Learn significant lore about a person, place, or object.' }),
  S('mass-cure-wounds', 'Mass Cure Wounds', 5, 'Evocation', 'bcd', 'healing', { r: '60 feet', heal: '3d8 + ability', x: 'Up to six creatures in a 30-foot radius regain 3d8 + your spellcasting ability modifier hit points.' }),
  S('mislead', 'Mislead', 5, 'Illusion', 'bw', 'mobility', { d: '1 hour', c: 'S', conc: true, x: 'Become invisible while an illusory double moves in your place.' }),
  S('planar-binding', 'Planar Binding', 5, 'Abjuration', 'bcdw', 'utility', { t: '1 hour', r: '60 feet', d: '24 hours', c: 'V, S, M', save: 'cha', x: 'Bind a celestial, elemental, fey, or fiend to your service.' }),
  S('raise-dead', 'Raise Dead', 5, 'Necromancy', 'bcp', 'healing', { t: '1 hour', r: 'Touch', c: 'V, S, M', x: 'Return a creature dead no more than 10 days to life with 1 hit point.' }),
  S('scrying', 'Scrying', 5, 'Divination', 'bcdkw', 'exploration', { t: '10 minutes', d: '10 minutes', c: 'V, S, M', conc: true, save: 'wis', x: 'See and hear a creature you choose, anywhere on the same plane.' }),
  S('seeming', 'Seeming', 5, 'Illusion', 'bsw', 'social', { r: '30 feet', d: '8 hours', save: 'cha', x: 'Change the appearance of any number of creatures you can see.' }),
  S('telekinesis', 'Telekinesis', 5, 'Transmutation', 'sw', 'control', { r: '60 feet', d: '10 minutes', conc: true, save: 'str', x: 'Move a creature or object of up to 1,000 pounds with your mind.' }),
  S('wall-of-force', 'Wall of Force', 5, 'Evocation', 'w', 'defense control', { r: '120 feet', d: '10 minutes', c: 'V, S, M', conc: true, x: 'An invisible wall of force that nothing can pass through physically.' }),
  S('wall-of-stone', 'Wall of Stone', 5, 'Evocation', 'dsw', 'control', { r: '120 feet', d: '10 minutes', c: 'V, S, M', conc: true, x: 'A stone wall of ten 10-foot panels that becomes permanent if maintained.' }),

  // --- 6th level --------------------------------------------------------------
  S('blade-barrier', 'Blade Barrier', 6, 'Evocation', 'c', 'damage control', { r: '90 feet', d: '10 minutes', conc: true, save: 'dex', dmg: '6d10 slashing', x: 'A wall of whirling blades deals 6d10 slashing damage and is difficult terrain.' }),
  S('chain-lightning', 'Chain Lightning', 6, 'Evocation', 'sw', 'damage', { r: '150 feet', c: 'V, S, M', save: 'dex', dmg: '10d8 lightning', x: 'A bolt strikes one creature and leaps to three more; 10d8 lightning damage on a failed Dexterity save.' }),
  S('circle-of-death', 'Circle of Death', 6, 'Necromancy', 'ksw', 'damage', { r: '150 feet', c: 'V, S, M', save: 'con', dmg: '8d6 necrotic', x: 'A 60-foot-radius sphere of negative energy dealing 8d6 necrotic damage.' }),
  S('disintegrate', 'Disintegrate', 6, 'Transmutation', 'sw', 'damage', { r: '60 feet', c: 'V, S, M', save: 'dex', dmg: '10d6+40 force', x: 'A thin green ray deals 10d6 + 40 force damage; a creature reduced to 0 hit points is disintegrated.' }),
  S('globe-of-invulnerability', 'Globe of Invulnerability', 6, 'Abjuration', 'sw', 'defense', { r: 'Self (10-foot radius)', d: '1 minute', c: 'V, S, M', conc: true, x: 'Spells of 5th level or lower cannot affect anything inside the barrier.' }),
  S('harm', 'Harm', 6, 'Necromancy', 'c', 'damage', { r: '60 feet', save: 'con', dmg: '14d6 necrotic', x: 'Inflict 14d6 necrotic damage and reduce the target’s hit point maximum accordingly.' }),
  S('heal', 'Heal', 6, 'Evocation', 'cd', 'healing', { r: '60 feet', heal: '70', x: 'A creature regains 70 hit points and is cured of blindness, deafness, and disease.' }),
  S('heroes-feast', "Heroes' Feast", 6, 'Conjuration', 'cd', 'support', { t: '10 minutes', r: '30 feet', c: 'V, S, M', x: 'A feast that cures disease and poison, grants immunity to fear, and raises hit point maximums by 2d10.' }),
  S('mass-suggestion', 'Mass Suggestion', 6, 'Enchantment', 'bksw', 'social control', { r: '60 feet', d: '24 hours', c: 'V, M', save: 'wis', x: 'Suggest a course of action to up to twelve creatures at once.' }),
  S('sunbeam', 'Sunbeam', 6, 'Evocation', 'dsw', 'damage', { r: 'Self (60-foot line)', d: '1 minute', c: 'V, S, M', conc: true, save: 'con', dmg: '6d8 radiant', x: 'A beam of brilliant light deals 6d8 radiant damage and blinds on a failed Constitution save.' }),
  S('true-seeing', 'True Seeing', 6, 'Divination', 'bcksw', 'utility', { r: 'Touch', d: '1 hour', c: 'V, S, M', x: 'The target gains truesight out to 120 feet.' }),
  S('wall-of-ice', 'Wall of Ice', 6, 'Evocation', 'w', 'control damage', { r: '120 feet', d: '10 minutes', c: 'V, S, M', conc: true, save: 'dex', dmg: '10d6 cold', x: 'A wall of ice that deals 10d6 cold damage to creatures in its space and blocks movement.' }),

  // --- 7th level --------------------------------------------------------------
  S('delayed-blast-fireball', 'Delayed Blast Fireball', 7, 'Evocation', 'sw', 'damage', { r: '150 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'dex', dmg: '12d6 fire', x: 'A bead that accumulates 1d6 fire damage each round before detonating.' }),
  S('etherealness', 'Etherealness', 7, 'Transmutation', 'bcksw', 'mobility', { d: 'Up to 8 hours', x: 'Step into the Ethereal Plane, able to move through solid matter.' }),
  S('finger-of-death', 'Finger of Death', 7, 'Necromancy', 'ksw', 'damage', { r: '60 feet', save: 'con', dmg: '7d8+30 necrotic', x: '7d8 + 30 necrotic damage; a humanoid killed rises as a zombie under your control.' }),
  S('fire-storm', 'Fire Storm', 7, 'Evocation', 'cds', 'damage', { r: '150 feet', save: 'dex', dmg: '7d10 fire', x: 'Ten 10-foot cubes of roaring flame deal 7d10 fire damage.' }),
  S('plane-shift', 'Plane Shift', 7, 'Conjuration', 'cdksw', 'mobility', { r: 'Touch', c: 'V, S, M', save: 'cha', x: 'Transport yourself and up to eight willing creatures to another plane.' }),
  S('prismatic-spray', 'Prismatic Spray', 7, 'Evocation', 'sw', 'damage control', { r: 'Self (60-foot cone)', save: 'dex', dmg: '10d6', x: 'Eight rays of coloured light, each with a different effect from 10d6 damage to petrification or banishment.' }),
  S('regenerate', 'Regenerate', 7, 'Transmutation', 'bcd', 'healing', { t: '1 minute', r: 'Touch', c: 'V, S, M', heal: '4d8 + 15', x: 'Restore 4d8 + 15 hit points, then 1 hit point per turn for an hour, regrowing severed limbs.' }),
  S('resurrection', 'Resurrection', 7, 'Necromancy', 'bc', 'healing', { t: '1 hour', r: 'Touch', c: 'V, S, M', x: 'Return a creature dead no more than a century to life with all its hit points.' }),
  S('teleport', 'Teleport', 7, 'Conjuration', 'bsw', 'mobility', { r: '10 feet', c: 'V', x: 'Transport yourself and up to eight willing creatures to a destination you know.' }),

  // --- 8th level --------------------------------------------------------------
  S('antimagic-field', 'Antimagic Field', 8, 'Abjuration', 'cw', 'defense control', { r: 'Self (10-foot radius)', d: '1 hour', c: 'V, S, M', conc: true, x: 'Spells and magical effects are suppressed within the sphere.' }),
  S('dominate-monster', 'Dominate Monster', 8, 'Enchantment', 'bksw', 'control', { r: '60 feet', d: '1 hour', conc: true, save: 'wis', x: 'Charm any creature and issue it commands.' }),
  S('earthquake', 'Earthquake', 8, 'Evocation', 'cds', 'damage control', { r: '500 feet', d: '1 minute', c: 'V, S, M', conc: true, save: 'dex', x: 'A seismic disturbance in a 100-foot radius knocks creatures prone and opens fissures.' }),
  S('feeblemind', 'Feeblemind', 8, 'Enchantment', 'bdkw', 'control', { r: '150 feet', c: 'V, S, M', save: 'int', dmg: '4d6 psychic', x: '4d6 psychic damage, and on a failed Intelligence save the target’s Intelligence and Charisma become 1.' }),
  S('holy-aura', 'Holy Aura', 8, 'Abjuration', 'c', 'defense support', { d: '1 minute', c: 'V, S, M', conc: true, x: 'Allies gain advantage on saves, attackers have disadvantage, and fiends and undead may be blinded.' }),
  S('power-word-stun', 'Power Word Stun', 8, 'Enchantment', 'bksw', 'control', { r: '60 feet', c: 'V', save: 'con', x: 'A creature with 150 hit points or fewer is stunned, with no save to resist the initial effect.' }),
  S('sunburst', 'Sunburst', 8, 'Evocation', 'dsw', 'damage', { r: '150 feet', c: 'V, S, M', save: 'con', dmg: '12d6 radiant', x: 'Brilliant sunlight in a 60-foot radius deals 12d6 radiant damage and blinds on a failed save.' }),

  // --- 9th level --------------------------------------------------------------
  S('foresight', 'Foresight', 9, 'Divination', 'bdkw', 'support', { t: '1 minute', r: 'Touch', d: '8 hours', c: 'V, S, M', x: 'The target has advantage on attacks, checks, and saves, and attacks against it have disadvantage.' }),
  S('gate', 'Gate', 9, 'Conjuration', 'csw', 'utility', { r: '60 feet', d: '1 minute', c: 'V, S, M', conc: true, x: 'A portal to another plane, through which creatures can travel.' }),
  S('imprisonment', 'Imprisonment', 9, 'Abjuration', 'kw', 'control', { t: '1 minute', r: '30 feet', d: 'Until dispelled', c: 'V, S, M', save: 'wis', x: 'Bind a creature in a chain, a burial, a slumber, or a demiplane.' }),
  S('mass-heal', 'Mass Heal', 9, 'Evocation', 'c', 'healing', { r: '60 feet', heal: '700', x: 'Distribute 700 hit points of healing among creatures you can see.' }),
  S('meteor-swarm', 'Meteor Swarm', 9, 'Evocation', 'sw', 'damage', { r: '1 mile', save: 'dex', dmg: '20d6 fire + 20d6 bludgeoning', x: 'Four blazing spheres each deal 20d6 fire and 20d6 bludgeoning damage in a 40-foot radius.' }),
  S('power-word-kill', 'Power Word Kill', 9, 'Enchantment', 'bksw', 'damage', { r: '60 feet', c: 'V', x: 'A creature with 100 hit points or fewer dies instantly.' }),
  S('time-stop', 'Time Stop', 9, 'Transmutation', 'sw', 'utility', { c: 'V', x: 'Take 1d4 + 1 turns in a row while time stands still for everyone else.' }),
  S('true-polymorph', 'True Polymorph', 9, 'Transmutation', 'bkw', 'control', { r: '30 feet', d: '1 hour', c: 'V, S, M', conc: true, save: 'wis', x: 'Transform a creature into another creature or an object, permanently if maintained.' }),
  S('wish', 'Wish', 9, 'Conjuration', 'sw', 'utility', { r: 'Self', c: 'V', x: 'The mightiest spell: duplicate any spell of 8th level or lower, or alter reality at a price.' }),
];

export const SPELLS = [...SPELLS_LOW, ...SPELLS_MID, ...SPELLS_HIGH];
